Add screen to choose application to import settings from
story-apps/starc pull request #129
Opened 2023-06-29 20:00 UTC by Alximik90

2023-06-30 09:52 UTC, dimkanovikov requested changes
Посмотрел. В целом всё хорошо - есть по мелочи некоторые нюансы.

Плюс посмотри форматирование - в корне проекта лежил clang-format файл, который нужно использовать, для автоформатирования.

2023-06-30 09:52 UTC, dimkanovikov commented on src/corelib/data_layer/storage/settings_storage.cpp
> +                         "Trelby;f2f2f21f1f1fda924bfffffff2f2f21f1f1f1f3142b5c1cdec3740f8f8f2000000f8f8f2182430d3dce9;");
Предлагаю это не хранить тут, а прямо во вьюху положить мапу в анонимный неймспейс, ведь оно понадобится нам только на этом экране

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.h
> +    Ui::ApplicationTheme selectedTheme;
это надо положить внутрь `d`

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.h
> +    Ui::ApplicationTheme getSelectedTheme() const;
выбранная тема используется только внутри класса - нет нужны прокидывать для неё метод в интерфейс, всё можно перенести внутрь файла реализации

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.h
> +enum class ApplicationToImportSettings;
Кажется это тут не нужно

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.cpp
> +            selectedTheme = _theme;
это можно объединить с предыдущим коннектом в одну лямбду

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.cpp
> +const std::unordered_map<QString, QString>& getCompetitirColorSchemes(Ui::ApplicationTheme _theme) {
тут typo `competitir` -> `competitor`

плюс предлагаю использовать Qt контейнеры (если конечно это не какой-то особенный случай и у этого выбора есть прям чёткие причины), в данном случае QHash

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.cpp
> +}
Да. будет круто вообще весь этот метод заменить просто на справочник типа

```
struct CompetitorInfo {
QString name;
QString lightThemeHash;
QString darkThemeHash;
};
const QVector<CompetitorInfo> kCompetitors = { { "KIT Scenarist", "light_hash", "dark_hash" }, ... };
```

И потом просто из него брать всё что нужно.

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.cpp
> +        d->styleChooseComboBox->setReadOnly(!_checked);
при включении (и выключении) тема сразу должна адаптироваться, кажется сейчас этого не будет происходить

2023-06-30 09:52 UTC, dimkanovikov commented on src/core/management_layer/content/onboarding/onboarding_manager.h
> +    void themeChangedCustom(QString _color);
тут с неймингом немного бы поигрался :) что-то типа `customThemeChanged` или `useCustomThemeRequested`

2023-07-02 20:02 UTC, Alximik90 commented on src/core/ui/onboarding/onboarding_navigator.h
> +    Ui::ApplicationTheme selectedTheme;
она должна перезаписываться при выборе темы на первом экране, так что используется и в навигаторе и в имплементации, я бы предпочёл оставить здесь, ибо в имплементации только визуальные элементы живут

2023-07-02 20:05 UTC, Alximik90 commented on src/corelib/data_layer/storage/settings_storage.cpp
> +                         "Trelby;f2f2f21f1f1fda924bfffffff2f2f21f1f1f1f3142b5c1cdec3740f8f8f2000000f8f8f2182430d3dce9;");
предлагаю не хранить тут а сделать загрузку настроек умолчания (или любых других) из файла, а то как-то не солидно :)

2023-07-03 19:18 UTC, dimkanovikov commented on src/corelib/data_layer/storage/settings_storage.cpp
> +                         "Trelby;f2f2f21f1f1fda924bfffffff2f2f21f1f1f1f3142b5c1cdec3740f8f8f2000000f8f8f2182430d3dce9;");
а в чём солидность будет? эти строчки нужны только в одном единственном месте программы, не очень понимаю зачем нужно их грузить из файла? какой это даст профит?

2023-07-03 19:19 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.h
> +    Ui::ApplicationTheme selectedTheme;
положить внутрь `d` я имел в виду, тут все данные класса инкапсулированы в pimpl-объекте

2023-07-03 19:21 UTC, dimkanovikov commented on src/core/management_layer/content/onboarding/onboarding_manager.h
> +    void useCustomThemeRequested(QString _color);
предлагаю тут имя переменной дать `_hash`, всё таки там целый набор цветов, плюс сделать константной ссылкой

2023-07-03 19:22 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.cpp
> +#include <map>
это больше не нужно

2023-07-03 19:23 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.cpp
> +            emit OnboardingNavigator::themeChanged(_theme);
тут можно просто `emit themeChanged(_theme)`

2023-07-03 19:24 UTC, dimkanovikov commented on src/core/ui/onboarding/onboarding_navigator.h
> +    Ui::ApplicationTheme getSelectedTheme() const;
up

2023-07-11 02:37 UTC, merged