Improve search in novel text
story-apps/starc pull request #212
Opened 2024-03-29 06:08 UTC by iljukhaput

When the search is opened, the text in the input panel becomes highlighted. Moreover, if text is selected in the editor, it is entered into the input field.

2024-03-29 10:49 UTC, dimkanovikov requested changes

2024-03-29 10:49 UTC, dimkanovikov commented on src/core/management_layer/plugins/novel_text/novel_text_view.h
> +    void switchToSearchTollbar();
этот метод не используется ни кем из клиентов, поэтому предлагаю его убрать из интерфейса и перенести в приватную часть

2024-03-29 10:49 UTC, dimkanovikov commented on src/core/management_layer/plugins/novel_text/novel_text_view.cpp
> +        = static_cast<NovelTextSearchToolbar*>(d->searchManager->toolbar());
когда приводим типы объекта наследника `QObject`, правильней использовать `qobject_cast`, также объявить объект можно просто `auto`, тут не может быть других вариантов для вывода типа

2024-03-29 10:49 UTC, dimkanovikov commented on src/core/management_layer/plugins/novel_text/novel_text_view.cpp
> +    if (!selectedText.isEmpty()) {
тут во-первых строку нужно сделать константной, а во вторых я бы предложил её инициилизацию прямо в `if` засунуть

2024-03-29 13:39 UTC, iljukhaput commented on src/core/management_layer/plugins/novel_text/novel_text_view.h
> +    void switchToSearchTollbar();
+

2024-03-29 13:39 UTC, iljukhaput commented on src/core/management_layer/plugins/novel_text/novel_text_view.cpp
> +        = static_cast<NovelTextSearchToolbar*>(d->searchManager->toolbar());
+

2024-03-29 13:39 UTC, iljukhaput commented on src/core/management_layer/plugins/novel_text/novel_text_view.cpp
> +    if (!selectedText.isEmpty()) {
+

2024-03-29 19:51 UTC, dimkanovikov commented on src/core/management_layer/plugins/novel_text/novel_text_view.cpp
> +    if (!selectedText.isEmpty()) {
тут чутка другое предлагал, вот такую конструкцию

```
if (const auto selectedText = d->textEdit->textCursor().selectedText(); !selectedText.isEmpty()) {
    ...
}
```

2024-03-30 09:43 UTC, iljukhaput commented on src/core/management_layer/plugins/novel_text/novel_text_view.cpp
> +    if (!selectedText.isEmpty()) {
исправил

2024-03-30 11:46 UTC, merged