Set Ctrl+C/Ctrl+X for the paragraph
story-apps/starc pull request #216
Opened 2024-04-04 13:54 UTC by iljukhaput

If selection is empty Ctrl+C/Ctrl+X applies to the paragraph

2024-04-04 14:06 UTC, dimkanovikov commented
А в базовом классе редактора это не получится сделать?

2024-04-09 06:09 UTC, dimkanovikov requested changes

2024-04-09 06:09 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +#include <business_layer/document/text/text_cursor.h>
Смотри, ты в чистый UI класс библиотеку пытаешься положить класс из уровня бизнес логики - это не очень гуд, тем более, что там даже не используется какая-то специфичная логика, которая в нём есть. В данном случае лучше использовать обычный QTextCursor - его будет достаточно.

2024-04-09 06:09 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +#include <QClipboard>
это больше не нужно

2024-04-09 06:09 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +        int position = cursor.position();
`const int` - это хорошее правило по-умолчанию использовать константы

2024-04-09 06:09 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +        cursor.clearSelection();
тут можно выделение не очищать, при задании позиции (на строку нижу) оно сделается автоматом

2024-04-09 06:59 UTC, iljukhaput commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +#include <business_layer/document/text/text_cursor.h>
Исправил

2024-04-09 07:00 UTC, iljukhaput commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +#include <QClipboard>
Убрал

2024-04-09 07:00 UTC, iljukhaput commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +        int position = cursor.position();
Исправил

2024-04-09 07:00 UTC, iljukhaput commented on src/corelib/ui/widgets/text_edit/base/base_text_edit.cpp
> +        cursor.clearSelection();
Исправил

2024-04-09 07:42 UTC, merged