Added a basic implementation of the MenuBar of the File menu and added the Preference activity to the main menu.
story-apps/starc pull request #218
Opened 2024-04-08 07:05 UTC by MlDenis

2024-04-10 18:14 UTC, dimkanovikov requested changes

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    QAction* aboutAppAction = new QAction(tr("About Story Architect"), this);
предлагаю это действие перенести ко всем остальным и завязать клик на ссылке `d->aboutApp` с вызовом данного действия, таким образом мы не будем два раза делать одно и то же действие в разных местах

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    QAction* preferencesAction = appMenu->addAction("Preferences");
вот это действие не понял зачем нам нужно - оно дублирует функционал действия `d->settings`, и, на сколько я понял, не добавляется в меню

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    fileMenu->addAction(d->projects);
предлагаю тут сузить контекстное окно для создаваемых объектов, не создавать все основные пункты меню вверху, а делать это по мере использования:

- создали пункт меню Story Architect
- наполнили его

- создали пункт меню Файл
- наполнили его

...

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->signIn);
предлагаю эти действия также положить в главный пункт меню Story Architect

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->writingSprint);
чтобы эти действия корректно отображались в меню, нужно для них задать тексты в методе `updateTranslations`

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        QMenuBar* menuBar = nullptr;
предлагаю создание менюшки вынести прямо в метод его инициилизации, т.к. она по-сути больше нигде и не будет использоваться

2024-04-10 18:14 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        menuBar(new QMenuBar)
соответственно это тоже станет более неактуальным

2024-04-12 08:37 UTC, MlDenis commented on src/core/management_layer/application_manager.cpp
> +#include <QMainWindow>
Исправил

2024-04-12 08:37 UTC, MlDenis commented on src/core/management_layer/application_manager.cpp
> +        Log::info("Incorrect use of the saveAs method");
Исправил

2024-04-12 08:37 UTC, MlDenis commented on src/core/management_layer/application_manager.cpp
> +    // строк итут некорректно
Исправил

2024-04-12 08:37 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +
Исправил

2024-04-12 09:35 UTC, MlDenis commented on src/core/ui/menu_view.h
> +    void createMenuBar();
Исправил

2024-04-12 09:50 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +    QAction* preferencesAction = appMenu->addAction("Preferences");
Исправил. Я по невнимательности продублировал действия. Изначально вот это пробовал (  appMenu->addAction(d->settings)), но оно не дало появления экшена в меню баре

2024-04-12 09:50 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +    fileMenu->addAction(d->projects);
Готово

2024-04-12 09:53 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->signIn);
Положил. Есть проблема, в главном меню получается добавить только два пункта. Остальные не отображаются. Есть идеи как это можно поправить?

2024-04-12 09:55 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->writingSprint);
А имеет ли это смысл, если они используют тексты, которые генерируют пункты основного меню? Для меню ведь всё задано и в других пунктах все корректно отображается без дополнительного задания текстов в updateTranslations

2024-04-12 10:40 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->writingSprint);
Сейчас в менюшке приложения они отображаются чисто как иконка - в меню системном нужно, чтобы у них был текст/название, иначе это будет очень странно выглядеть

2024-04-12 10:42 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->signIn);
а что с ними происходит при этом? совсем ничего в меню не добавляется?

2024-04-12 12:23 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->signIn);
Бывает что совсем ничего. Бывает, что добавляется одноименное меню и оставшиеся пункты прячутся туда, если больше двух пунктов

2024-04-15 07:51 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        d->menuBar->update();
Исправлено. В обновленной реализации обновляется автоматически

2024-04-15 07:51 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        d->menuBar->update();
Исправлено. В обновленной реализации обновляется автоматически

2024-04-15 07:51 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +    #ifdef Q_OS_MAC
Готово

2024-04-15 07:51 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        menuBar(new QMenuBar)
Готово

2024-04-15 07:51 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        QMenuBar* menuBar = nullptr;
Готово

2024-04-15 09:11 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +        actionsMenu->addAction(d->writingSprint);
Готово

2024-04-15 10:25 UTC, dimkanovikov requested changes

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    }
там выше идёт комментарий к коду, который ниже проверки, предлагаю поместить проверку над комментарием

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    MenuView* q;
обрати пожалуйста внимание, в описании класса Implementation у нас сверху идут методы, а потом данные

q - обычно ставится первым из всех параметров класса реализации

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    , q(dynamic_cast<MenuView*>(_parent))
можно сразу в описании метода нужный тип задать, зачем тут приведение типов делать?

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +
выше писал про пустые изменённые строки - лучше их избегать

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    // Добавляем ManuBar
typo: MenuBar

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    d->signIn->setText(tr("SignIn"));
у него уже выше задаётся текст

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +#include "ui/settings/settings_view.h"
зачем нужен этот инклуд?

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +// Создание MenuBar
вот такие коменты перед названием реализации метода мы не оставляем, лучше сделать это в интерфейсе класса используя нотацию doxygen

2024-04-15 10:25 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        QMenuBar* menuBar = nullptr;
Не совсем то, как я предложил - надо QAction положить внутрь d, сигнал нажатия на ссылке завязать на сигнал активации экшена, а сигнал самого экшена привязать к коду отображения диалога о программе. Сейчас получилось наоборот, активация экшена приводит к клику на ссылке, что кажется не совсем логичным

2024-04-15 11:05 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +        QMenuBar* menuBar = nullptr;
не туда коммент добавил

2024-04-15 11:06 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    QAction* aboutAppAction = new QAction(tr("About Story Architect"), this);
Не совсем то, как я предложил - надо QAction положить внутрь d, сигнал нажатия на ссылке завязать на сигнал активации экшена, а сигнал самого экшена привязать к коду отображения диалога о программе. Сейчас получилось наоборот, активация экшена приводит к клику на ссылке, что кажется не совсем логичным

2024-04-15 14:17 UTC, MlDenis commented on src/core/management_layer/application_manager.cpp
> +    }
Готово

2024-04-15 14:17 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +
Исправил

2024-04-15 14:17 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +    // Добавляем ManuBar
Исправил

2024-04-15 14:17 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +    d->signIn->setText(tr("SignIn"));
Исправил

2024-04-15 14:17 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +#include "ui/settings/settings_view.h"
Исправил

2024-04-15 14:28 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +// Создание MenuBar
Исправил

2024-04-15 14:32 UTC, MlDenis commented on src/core/ui/menu_view.cpp
> +    , q(dynamic_cast<MenuView*>(_parent))
Готово

2024-04-16 09:26 UTC, dimkanovikov commented on src/core/ui/menu_view.cpp
> +    connect(aboutAppAction, &QAction::triggered, aboutApplicationAction, &QAction::triggered);
а зачем тут создавать ещё одно действие? можно просто `aboutApplicationAction` в меню положить?

2024-04-16 09:48 UTC, dimkanovikov approved these changes

2024-04-16 09:49 UTC, merged