Add ability to remove set of documents
story-apps/starc pull request #221
Opened 2024-04-09 12:36 UTC by iljukhaput

2024-04-09 14:24 UTC, dimkanovikov requested changes

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    void removeDocuments();
тут тоже надо больше контекста - вот в комментарии хорошо, а в названии неочень, `removeSelectedDocuments` было бы гораздо более понятно

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
>              auto removeDocument = new QAction(tr("Remove document"));
может тут условным оператором сделать задание названия сразу?)

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (navigator->selectedIndexes().count() > 1) {
`count` обычно для подсчёта используют, если нужно размер, то лучше использовать `size` или `length` - так более общепринято что ли

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (_index.isValid() && canBeRemoved(currentItem)) {
смотри, сейчас пункт меню появится, только если вызвать контекстное меню щёлкнув на тот элемент, который можно удалить, а если будет выделено несколько элементов и щёлкнуть на тот, который удалить нельзя, то пункта не появится, а по идее должен быть

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        auto tmp = itemIndex;
такие бессмысленные названия лучше в принципе не использовать, тут больше подойдёт `parentItemIndex` или что-то в этом роде

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            return;
почему `return`  а не `continue`?

2024-04-09 14:24 UTC, dimkanovikov commented on src/core/ui/project/project_navigator.h
> +#include <QModelIndexList>
нужно использовать forward declaration для подобных случаев

2024-04-09 16:25 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +bool canBeRemoved(BusinessLayer::StructureModelItem* _item)
исправил

2024-04-09 16:25 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    void removeDocuments();
исправил

2024-04-09 16:25 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
>              auto removeDocument = new QAction(tr("Remove document"));
исправил

2024-04-09 16:25 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (_index.isValid() && canBeRemoved(currentItem)) {
исправил

2024-04-09 16:25 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        auto tmp = itemIndex;
исправил

2024-04-09 16:25 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            return;
ошибся, исправил

2024-04-09 16:26 UTC, iljukhaput commented on src/core/ui/project/project_navigator.h
> +#include <QModelIndexList>
заменил на синоним `QList<QModelIndex>`,  при forward declaration ругается на переопределение...
Если такой вариант не подходит, буду разбираться, почему ругается
![image](https://github.com/story-apps/starc/assets/81326673/540fc8b3-f3b7-4c12-8e44-8370b920e697)

2024-04-10 17:44 UTC, dimkanovikov commented on src/core/ui/project/project_navigator.h
> +#include <QModelIndexList>
видимо из-за того, что QModelIndexList это дефайн, но так как сделал пойдёт

2024-04-10 17:44 UTC, merged