Add export simple text to markdown
story-apps/starc pull request #226
Opened 2024-04-17 16:37 UTC by iljukhaput

2024-04-17 16:46 UTC, iljukhaput commented
Пока черновой вариант.
Почему-то если стандартный заголовок (не зачеркнутый, не курсив), то не считывается, что он полужирный (а он именно полужирный по умолчанию), но если сделать его курсивом, например, то считается и то, что курсив, и то, что полужирный.
Завтра как минимум буду с утра с этим разбираться и добавлю возможность экспорта только выделенного текста.
Ну и если будут правки сегодня, то и с правками)

Ещё сомнения по текстовой заметке - сейчас она форматируется как цитата.

2024-04-18 02:26 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static QString formatsDiffToString(const QTextCharFormat& _current, const QTextCharFormat& _next)
Так, заметил, что эта функция уже нигде не используется больше, исправлю)

2024-04-18 03:42 UTC, dimkanovikov requested changes

2024-04-18 03:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    QSet<QChar> escapedCharacters
const

2024-04-18 03:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static void escapeCharacters(QString& _paragraph, const int _begin, const int _end)
простые типы не принято константными передавать в методы

2024-04-18 03:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static QString openFormatToString(const QTextCharFormat& _format)
а реально есть разница в каком порядке идут метки форматирования?

2024-04-18 03:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +        paragraphText = paragraphText.trimmed();
зачем? и тут ещё был момент с заменой `LineSeparator` на `LineFeed`, почему решил его убрать?

2024-04-18 03:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            paragraphText.prepend("# ");
смотри, сейчас заголовок будет вставляться без пустой строки от предыдущего текста, т.е. если сначала идёт простой текст, а потом заголовок, то будет так

```
Обычный текст.
# Заголовок
```

на мой взгляд, читабельности файлу придаст добавление переносов строки перед заголовками

2024-04-18 03:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +        case TextParagraphType::InlineNote: {
давай блоки заметок будем опускать, т.к. маркдаун не умеет в комментарии

2024-04-18 03:42 UTC, dimkanovikov commented on src/core/ui/export/simple_text_export_dialog.cpp
> +            isWatermarkVisible = false;
тут предлагаю также скрыть и возможность печатать заметки по тексту, т.к. маркдаун не умеет в комментарии

2024-04-18 05:25 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static QString openFormatToString(const QTextCharFormat& _format)
в исключительном случае, когда ко всему блоку целиком применяются несколько форматов
например **_Жирный курсив_**, если не форматировать в обратном порядке экспортируется в _**Жирный курсив_**

2024-04-18 08:52 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static QString openFormatToString(const QTextCharFormat& _format)
окей

2024-04-18 14:02 UTC, iljukhaput commented on src/core/ui/export/simple_text_export_dialog.cpp
> +            isWatermarkVisible = false;
сделал

2024-04-18 14:03 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +        case TextParagraphType::InlineNote: {
сделал

2024-04-18 14:03 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            paragraphText.prepend("# ");
Сделал в виде вставки пустой строки, если она была и в исходном тексте.
    if (block.text().isEmpty()) {
        markdownFile.write("\n");
        continue;
    }

2024-04-18 14:04 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static void escapeCharacters(QString& _paragraph, const int _begin, const int _end)
исправил

2024-04-18 14:04 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    QSet<QChar> escapedCharacters
исправил

2024-04-18 14:04 UTC, iljukhaput commented on src/core/ui/export/simple_text_export_dialog.cpp
> +        case 2: {
сделал

2024-04-18 14:04 UTC, iljukhaput commented on src/core/ui/export/simple_text_export_dialog.cpp
> +    }
исправил

2024-04-18 14:05 UTC, iljukhaput commented on src/core/ui/export/simple_text_export_dialog.cpp
> +BusinessLayer::ExportFileFormat getFileFormat(const int _row)
сделал
имя `fileFormat` уже занято, поэтому назвал `currentFileFormat`

2024-04-18 14:11 UTC, iljukhaput commented
пока все еще черновой вариант - заметил, что в некоторых случаях при вложенных форматах отрабатывает некорректно

2024-04-19 03:08 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            paragraphText.prepend("# ");
но щас подумал, наверно лучше ещё добавить и просто вставку пустой строки перед заголовком

2024-04-19 05:17 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            paragraphText.prepend("# ");
Это не то, что я имел в виду. Такой вариант совсем кажется нелогичным, вот у меня пустой заголовок первого/шестого уровня, а вставляется просто пустая строка...

Я же предлагаю добавлять пустую строку перед заголовками, для формирования более читабельного маркдаун документа

2024-04-19 09:04 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            paragraphText.prepend("# ");
исправил

2024-04-19 09:05 UTC, iljukhaput commented on src/core/ui/export/simple_text_export_dialog.cpp
> +    BusinessLayer::ExportFileFormat currentFileFormat();
исправил

2024-04-19 09:05 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +        closeFormatIndex--;
исправил

2024-04-19 09:59 UTC, dimkanovikov requested changes

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            QString prefix("#");
const

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    for (int index = _formatIndex + 1; index < formats.size() && !currentFormats.isEmpty();
тут нужна проверка, не закончились ли текущие форматы, ибо форматы могут закончится в середине, а потом опять начаться

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            formatString.prepend("**");
предлагаю значки форматирования таки вынести в константы в анонимном неймспейсе

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    for (int index = _formatIndex - 1; index >= 0 && !currentFormats.isEmpty(); --index) {
тут такая же проблема - нужно добавить проверку не кончились ли текущие форматы

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    while (_paragraph.mid(index, 1) == " ") {
может проще `_paragraph[index].isSpace()`?

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    while (_paragraph.mid(index - 1, 1) == " ") {
тут тоже также можно упростить

2024-04-19 09:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            // ... если было, то сравниваем форматы и пишем только необходимое (то,
тут комментарий ещё странный, предлагаю переформулировать в стиле `если он есть` и на ветке else соответственно `... а если это последний формат блока, то...`

2024-04-19 11:23 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    for (int index = _formatIndex + 1; index < formats.size() && !currentFormats.isEmpty();
`&& !currentFormats.isEmpty();` - так вот же
или я неправильно понял?)

2024-04-19 12:27 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            QString prefix("#");
исправил

2024-04-19 12:27 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    for (int index = _formatIndex + 1; index < formats.size() && !currentFormats.isEmpty();
тут, получается, оставил как было)

2024-04-19 12:27 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            formatString.prepend("**");
вынес

2024-04-19 12:28 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +    while (_paragraph.mid(index, 1) == " ") {
исправил

2024-04-19 12:29 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +            // ... если было, то сравниваем форматы и пишем только необходимое (то,
исправил

2024-04-19 12:34 UTC, iljukhaput commented
опечатался в комментарии - перезалил

2024-04-19 14:27 UTC, dimkanovikov commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static const QVector<QPair<MarkdownFormats, QString>> formatSymbols{
к именам таких констант добавляем префикс `k`, в данном случае будет `kFormatSymbols`

2024-04-20 03:34 UTC, iljukhaput commented on src/corelib/business_layer/export/simple_text/simple_text_markdown_exporter.cpp
> +static const QVector<QPair<MarkdownFormats, QString>> formatSymbols{
исправил

2024-04-20 18:41 UTC, merged