Add novel export to the markdown
story-apps/starc pull request #228
Opened 2024-04-23 07:28 UTC by iljukhaput

2024-04-23 14:33 UTC, iljukhaput commented
забыл про экспорт текста в заданном интервале

2024-04-24 03:26 UTC, dimkanovikov commented on src/core/ui/export/novel_export_dialog.cpp
> +            isOrnamentalBreak = false;
погоди, погоди - зачем тут всё это отключать нам?

2024-04-24 03:26 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +enum MarkdownFormats {
может сделаем какой-нибудь `AbstractMarkdownExporter` уже?)

2024-04-24 03:33 UTC, iljukhaput commented on src/core/ui/export/novel_export_dialog.cpp
> +            isOrnamentalBreak = false;
я так понял пока экспортируем только сам текст романа. Или экспортируем все кроме титульной страницы?

2024-04-24 03:39 UTC, dimkanovikov commented on src/core/ui/export/novel_export_dialog.cpp
> +            isOrnamentalBreak = false;
ну как минимум видимость футеров и орнаментальные разрывы всегда актуальны, по остальным пунктам я бы тоже оставил их видимыми, чтобы пользователи нас пушили добавить экспорт титульной страницы) а синопсис/аутлайн должны уметь экспортироваться, да

2024-04-24 13:29 UTC, iljukhaput commented on src/core/ui/export/novel_export_dialog.cpp
> +            isOrnamentalBreak = false;
исправил

2024-04-24 13:30 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +enum MarkdownFormats {
пока не сделал ещё, но, так понимаю, лучше отдельным коммитом залить?

2024-04-24 13:38 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +            auto blockFormat = block.blockFormat();
Переопределил, чтобы убрать сбрасывание типов здесь

2024-04-24 18:25 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +enum MarkdownFormats {
я предлагаю прямо в этом коммите сделать абстракнтый экспортер в формате мардаун, а потом отдельным реквестом перенести на него остальные экспортеры маркдаун/фонтан

2024-04-26 07:54 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +enum MarkdownFormats {
сделал

2024-04-27 02:46 UTC, dimkanovikov requested changes

2024-04-27 02:46 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
что-то я так и не пойму - зачем нам этот метод переопределять тут?

2024-04-27 02:46 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.h
> +    void exportTo(AbstractModel* _model, ExportOptions& _exportOptions) const override;
хотелось бы оба метода `exportTo` вынести в базовый/абстрактный класс

2024-04-27 02:51 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
в базовом классе в нем при добавлении синопсиса в документ сбрасываются типы выделения текста

2024-04-27 02:59 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
предлагаю это пофиксить в базовом тогда, ибо звучит как баг

2024-04-27 03:08 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
я пробовал, в этом случае сбивается экспорт в docx

2024-04-27 03:10 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
![image](https://github.com/story-apps/starc/assets/81326673/396c027c-2c97-4531-ab90-0b258d517c5c)

2024-04-27 03:21 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
давай заведём на это отдельную задачку и будем разбираться

2024-04-27 03:24 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
окей, принял

2024-04-27 05:45 UTC, iljukhaput commented on src/core/management_layer/plugins/novel_text/text/novel_text_edit.cpp
>  // #include <business_layer/export/novel/novel_fountain_exporter.h>
удалил

2024-04-27 05:45 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.h
> +    }
перенес

2024-04-27 05:46 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_exporter.h
> +    }
и тут перенес

2024-04-27 05:46 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    }
и тут перенес)

2024-04-27 05:48 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    TextDocument* prepareDocument(AbstractModel* _model,
тут переопределение убрал, а в базовом классе убрал сбрасывание типов выделения

2024-04-27 05:48 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.h
> +    void exportTo(AbstractModel* _model, ExportOptions& _exportOptions) const override;
вынес

2024-04-27 07:05 UTC, dimkanovikov requested changes
Плюс ещё один момент - синхронизируй пожалуйста последовательность методов в заголовочных файлах и файлах реализации

2024-04-27 07:05 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +        switch (TextBlockStyle::forBlock(block)) {
вот смотри, этот блок с формированием строки, в зависимости от формата, плюс запись пустых строк, по-хорошему нужно вынести в интерфейс абстрактного класса, а наследники должны реализовывать конкретную работу со своими типами

2024-04-27 07:05 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    static QString openFormatString(const QVector<QTextLayout::FormatRange>& formats,
этот и последующие методы не нужны в интерфейсе, т.к. они не будут использоваться снаружи

2024-04-27 07:05 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +        = { '\\', '`', '*', '_', '{', '}', '[', ']', '(', ')', '#', '+', '-', '.', '!', '|', '~' };
список симвлолав для экранирования также актуально прокинуть в интерфейс абстрактного класса

2024-04-27 07:05 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +QString AbstractMarkdownExporter::formatSymbols(TextSelectionTypes _type)
а также какой формат каким символом обозначать, тоже актуально для конкретных реализаций

2024-04-30 08:40 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +        switch (TextBlockStyle::forBlock(block)) {
сделал

2024-04-30 08:40 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    static QString openFormatString(const QVector<QTextLayout::FormatRange>& formats,
исправил

2024-04-30 08:41 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +        = { '\\', '`', '*', '_', '{', '}', '[', ']', '(', ')', '#', '+', '-', '.', '!', '|', '~' };
сделал

2024-04-30 08:46 UTC, iljukhaput commented
И последовательность методов в заголовочных файлах и файлах реализации синхронизировал

2024-04-30 09:42 UTC, dimkanovikov requested changes

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    constexpr int invalidPosition = -1;
невалидная позиция используется тут и ниже, предлагаю вынести константу в анонимный неймспейс

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    TextParagraphType previosBlockType = TextParagraphType::Undefined;
typo: previous

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    void setEscapedCharacters(QSet<QChar> _characters);
не понял, зачем так делать?) дай просто метод константный, который будет возвращать сет символов, которые нужно экранировать

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    void setEscapedCharacters(QSet<QChar> _characters);
либо прям в конструкторе тогда уже передать список - он же не будет изменяться во время выполнения, поэтому лучше его зафиксировать

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
зачем тут пробел вставлять?

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +    case TextParagraphType::BeatHeading: {
заголовки битов, предлагаю экспортировать как обычный текст, т.к. при выгрузке аутлайна, они по-сути будут основным текстом глав

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +        Heading,
считаю, что заголовкам тут не место всё таки, добавляя их сюда, мы смешиваем форматирование текста с форматом абзаца

2024-04-30 09:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    virtual bool formatBlock(QString& _paragraph, TextParagraphType _blockType) const = 0;
тут ещё предложил бы подумать над интерфейсом метода, сейчас в нём как будто смешаны два разных действия - форматирование и проверка, нужно ли блок записывать, более цельным кажется вариант `bool processBlock`, или что-то в этом роде, который будет возвращать `false`, если блок не был обработан, и в таких случаях обработка текста в абстрактом классе будет понимать, что блоки, которые не были обработаны, нам не нужны и мы их опускаем

2024-04-30 09:57 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
так в руководстве сказано: "Чтобы создать разрыв строки (<br>), завершите строку двумя или более пробелами, а затем нажмите Enter."

2024-04-30 10:01 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
ого! это в маркдауне так? не знал

2024-04-30 10:06 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
да, вот пруфы, если что)
[(https://daringfireball.net/projects/markdown/syntax#p)](url)

2024-05-02 07:36 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    virtual bool formatBlock(QString& _paragraph, TextParagraphType _blockType) const = 0;
исправил

2024-05-02 07:36 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +        Heading,
убрал

2024-05-02 07:37 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +    case TextParagraphType::BeatHeading: {
исправил

2024-05-02 07:38 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.h
> +    void setEscapedCharacters(QSet<QChar> _characters);
переделал - передаю в конструктор

2024-05-02 07:38 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    TextParagraphType previosBlockType = TextParagraphType::Undefined;
исправил

2024-05-02 07:38 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    constexpr int invalidPosition = -1;
вынес

2024-05-02 13:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    if (_fromPosition != -1 && _toPosition != -1 && _fromPosition < _toPosition) {
`kInvalidPosition`

2024-05-02 13:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    QSet<QChar> escapedCharacters;
чтобы прям вообще идеально было надо тут `const` пометить

2024-05-02 13:42 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
Это не то - тут речь идёт об инлайн-переводах, когда мы остаёмся в том же параграфе, но делаем перевод строки, `paragraphText = paragraphText.replace(QChar::LineSeparator, QChar::LineFeed);` как раз удаляет такие переносы у нас

2024-05-02 13:45 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
тут либо докручивать через вот эту тему, которую ты накопал, либо забить и не дописывать пробелы (я за второй вариант))))

2024-05-02 14:30 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
не совсем совсем понял, что именно докручивать? Сейчас же добавляются два пробела и перенос строки

2024-05-02 17:46 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
Блин, видать у меня инет в метро заглючил - там был коммент о том, что это немного не то. Два пробела и перенос строки нужны для кейса, когда внутри абзаца есть перенос строки, но он не делить его на два абзаца. А мы же все такие переносы строк принудительно считаем на разрыв абзаца (тот самый код, где мы меняем LineSeparator на LineFeed). Вот я и пишу, что тут либо докручивать корректные переносы, либо забить и просто не добавлять пробелы

2024-05-03 02:57 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_markdown_exporter.cpp
> +        _paragraph.append("  ");
исправил по второму варианту)

2024-05-03 02:58 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    if (_fromPosition != -1 && _toPosition != -1 && _fromPosition < _toPosition) {
исправил

2024-05-03 02:58 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +    QSet<QChar> escapedCharacters;
исправил

2024-05-03 02:58 UTC, iljukhaput commented on src/corelib/business_layer/export/abstract_markdown_exporter.cpp
> +        bool isProcessed = processBlock(paragraphText, TextBlockStyle::forBlock(block));
исправил

2024-05-03 05:21 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
Ой, а оно же должно само по себе работать, там выше (в `NovelExporter::createDocument`) уже идёт задание документу информации о том, что он аутлайн, а это в свою очередь должно приводить к тому, чтобы все блоки текста или заголовки битов были скрыты. Зачем тут это добавлять?

2024-05-03 05:24 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
А, я понял в чём дело, в экспортере фонтана не проверяется видимый ли блок или нет, потому что в фонтане например под это есть определённый формат, а в маркдауне нет. Давай тогда это через интерфейс абстрактного экспортера фонтана разведём как-то, нужно ли писать блоки невидимые или нет.

2024-05-03 05:28 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
при этом я бы сделал так

в романе при экспорте плана вырезается текст, при экспорте текста вырезается план

в сценарии при экспорте плана вырезается текст, при экспорте текста всё оставляем на месте и текст и биты

2024-05-03 05:34 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
понял, принял, сейчас исправлю

2024-05-03 11:55 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
сделал

2024-05-03 12:11 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
а как планируешь потом реализовать кейс экспорта сценария, когда нужны и биты и текст?)

2024-05-03 14:10 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
исправил, но меня не покидает ощущение, что слишком замудрено сделал (:

2024-05-03 16:32 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
Слушай, я посмотрел код и вообще говоря у нас уже есть подобное поведение вообще в `NovelExporter::prepareBlock`, давай туда и уберём удаление ненужных блоков, м?)

2024-05-06 02:33 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (const auto blockType = TextBlockStyle::forBlock(_cursor); exportOptions.includeOutline
исправил

2024-05-06 02:35 UTC, dimkanovikov commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (!_cursor.block().isVisible()) {
тут нужно возвращать true, чтобы следующий после удаляемого блок тоже попал в обработку, иначе, если у тебя идут подряд два невидимых блока, второй не будет удален

2024-05-06 02:47 UTC, iljukhaput commented on src/corelib/business_layer/export/novel/novel_exporter.cpp
> +    if (!_cursor.block().isVisible()) {
исправил

2024-05-06 02:52 UTC, dimkanovikov approved these changes

2024-05-06 02:53 UTC, merged