Added document export action from the context menu.
story-apps/starc pull request #231
Opened 2024-05-02 20:00 UTC by MlDenis

2024-05-03 05:10 UTC, dimkanovikov requested changes

2024-05-03 05:10 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +                bool _aviable = d->exportManager->canExportDocument(_model);
`const`

2024-05-03 05:10 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        auto exportCurrentFileAction = new QAction(tr("Export current file..."));
Предлагаю назвать его просто "Export..." а не "Export current file..."

2024-05-03 05:10 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +                [this] { q->exportCurrentDocumentPressed(); });
тут можно без лямбды сделать, а конектить сразу к сигналу класса

2024-05-03 05:10 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.h
> +    bool isCurrentDocumentExportAviable;
все данные класса должны быть скрыты в приватной части класса и находиться в реализации

2024-05-03 05:10 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.h
> +    void exportCurrentDocumentPressed();
`Pressed` используем для UI-компонентов, если обратишь внимание, то подобные сигналы в менеджерах имеют окончание `Requested`

2024-05-03 12:11 UTC, MlDenis commented on src/core/management_layer/application_manager.cpp
> +                bool _aviable = d->exportManager->canExportDocument(_model);
Исправил

2024-05-03 12:11 UTC, MlDenis commented on src/core/management_layer/content/project/project_manager.cpp
> +        auto exportCurrentFileAction = new QAction(tr("Export current file..."));
Исправил

2024-05-03 12:11 UTC, MlDenis commented on src/core/management_layer/content/project/project_manager.cpp
> +                [this] { q->exportCurrentDocumentPressed(); });
Исправил

2024-05-03 12:11 UTC, MlDenis commented on src/core/management_layer/content/project/project_manager.h
> +    bool isCurrentDocumentExportAviable;
Исправил

2024-05-03 12:11 UTC, MlDenis commented on src/core/management_layer/content/project/project_manager.h
> +    void exportCurrentDocumentPressed();
Исправил

2024-05-03 12:20 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    };
тут странная точка с запятой) надо убрать

2024-05-06 10:09 UTC, MlDenis commented on src/core/management_layer/content/project/project_manager.cpp
> +    };
Исправил

2024-05-06 14:51 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +                d->projectManager->setCurrentDocumentExportAviable(_aviable);
typo: available

2024-05-06 14:51 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    bool isCurrentDocumentExportAviable = false;
same

2024-05-07 07:28 UTC, MlDenis commented on src/core/management_layer/content/project/project_manager.cpp
> +    bool isCurrentDocumentExportAviable = false;
Исправил

2024-05-07 07:28 UTC, MlDenis commented on src/core/management_layer/application_manager.cpp
> +                d->projectManager->setCurrentDocumentExportAviable(_aviable);
Исправил

2024-05-07 09:13 UTC, merged