Import from markdown to novel
story-apps/starc pull request #241
Opened 2024-05-17 09:15 UTC by iljukhaput

2024-05-18 14:23 UTC, iljukhaput commented
добавил обработку футеров

2024-05-20 08:16 UTC, dimkanovikov requested changes

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/import_options.h
> +    ImportDocymentType documentType;
надо обязательно задать дефолтное значение, чтобы там не было мусора

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/novel/novel_import_options.h
> +struct CORE_LIBRARY_EXPORT NovelImportOptions : public ImportOptions {
если тут структура ничем не отличается, то тогда предлагаю выкинуть её

2024-05-20 08:16 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +    d->documentType->setLabel(tr("Import to"));
А ещё, видимо нужно показывать дополнительные галочки в зависимости от выбранного типа документа для импорта, например для романа, мы не умеем пока извлекать персонажей и локации, для всех остальных типов кроме сценария мы не умеем извлекать локации, но умеем персонажей

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/import_options.h
> +    bool keepSceneNumbers = false;
думаю, что это будет актуально только для сценариев

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/import_options.h
> +    bool importScreenplay = true;
может быть что-то типа `importText`?

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +    int length;
для простых типов обязательно задать дефолтные значения

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +            QCoreApplication::translate("KeyProcessingLayer::FolderFooterHandler", "End of"))) {
`QCoreApplication::translate("BusinessLayer::NovelMarkdownImporter", "End of"))` ?

2024-05-20 08:16 UTC, dimkanovikov commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +        QVector<QSharedPointer<SelectionTypeInText>> selectionTypesInText;
зачем тут шареды нужны?

2024-05-20 09:10 UTC, iljukhaput commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +        QVector<QSharedPointer<SelectionTypeInText>> selectionTypesInText;
я так рассуждал: объекты создаются внутри цикла, а будут использоваться после цикла, за пределами области видимости, в которой они были созданы, поэтому QScopedPointer использовать не получится. Остаются варианты: либо шареды, либо удалять вручную

2024-05-20 09:15 UTC, dimkanovikov commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +        QVector<QSharedPointer<SelectionTypeInText>> selectionTypesInText;
а почему не просто на стеке?)

2024-05-20 09:21 UTC, iljukhaput commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +        QVector<QSharedPointer<SelectionTypeInText>> selectionTypesInText;
чет перемудрил, да...
исправлю)

2024-05-20 15:57 UTC, iljukhaput commented on src/corelib/business_layer/import/import_options.h
> +enum class ImportDocymentType {
исправил

2024-05-20 15:58 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +        { tr("Simple text"), BusinessLayer::ImportDocymentType::SimpleText },
убрал

2024-05-20 15:58 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +    contentsLayout()->addLayout(d->buttonsLayout, 7, 0);
сделал

2024-05-20 15:58 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +        const QVector<QPair<QString, BusinessLayer::ImportDocymentType>> _types);
исправил

2024-05-20 15:59 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +    for (QPair type : _types) {
исправил

2024-05-20 15:59 UTC, iljukhaput commented on src/corelib/business_layer/import/novel/novel_import_options.h
> +struct CORE_LIBRARY_EXPORT NovelImportOptions : public ImportOptions {
выкинул

2024-05-20 15:59 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +    d->documentType->setLabel(tr("Import to"));
сделал

2024-05-20 16:00 UTC, iljukhaput commented on src/corelib/business_layer/import/import_options.h
> +    bool importScreenplay = true;
сделал

2024-05-20 16:00 UTC, iljukhaput commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +    int length;
исправил

2024-05-20 16:00 UTC, iljukhaput commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +            QCoreApplication::translate("KeyProcessingLayer::FolderFooterHandler", "End of"))) {
исправил

2024-05-20 16:00 UTC, iljukhaput commented on src/corelib/business_layer/import/novel/novel_markdown_importer.cpp
> +        QVector<QSharedPointer<SelectionTypeInText>> selectionTypesInText;
исправил

2024-05-21 04:57 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +    options.keepSceneNumbers = d->keepSceneNumbers->isVisible() && d->keepSceneNumbers->isChecked();
Может быть тут сделать что-то типа

```
BusinessLayer::ScreenplayImportOptions options = importOptions();
options.keepSceneNumbers = d->keepSceneNumbers->isVisible() && d->keepSceneNumbers->isChecked();
```

?

2024-05-21 04:57 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +    d->documentType->setLabel(tr("Import to"));
тут я бы предложил чуть красоту в коде навести, да уменьшить копипасту таким образом

```c++
auto fileIs = [filaPath = d->importFilePath.toLower()] (const QString& _extension) { 
    return filePath.endsWith(_extension); 
};

const auto audioplay = qMakePair(tr("Audioplay"), Domain::DocumentObjectType::Audioplay);
const auto comicBook = qMakePair(tr("Comic Book"), Domain::DocumentObjectType::ComicBook);
// ...

if (fileIs(ExtensionHelper::msOfficeOpenXml())
    || fileIs(ExtensionHelper::openDocumentXml())
    || fileIs(ExtensionHelper::plainText())) {
    d->setImportDocumentTypes({
        audioplay,
        comicBook,
        // ...
    });
}
```

2024-05-21 05:54 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +    d->documentType->setLabel(tr("Import to"));
сделал

2024-05-21 05:56 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +    options.keepSceneNumbers = d->keepSceneNumbers->isVisible() && d->keepSceneNumbers->isChecked();
сделал

2024-05-21 05:58 UTC, iljukhaput commented
и убрал обработку футеров сразу

2024-05-21 06:04 UTC, iljukhaput commented on src/core/management_layer/content/import/import_manager.cpp
> +                importDialog->hideDialog();
тут поменял местами, чтобы диалог был видимый, когда в импорт передаем опции, так как в `importOptions()` проверяются параметры по видимости

2024-05-21 06:08 UTC, dimkanovikov commented on src/core/management_layer/content/import/import_manager.cpp
> +                importDialog->hideDialog();
хех, в таких кейсах корректней будет использовать не просто `isVisible`, а `isVisibleTo` к самому диалогу, например

2024-05-21 06:08 UTC, dimkanovikov commented on src/core/management_layer/content/import/import_manager.cpp
> +                importDialog->hideDialog();
а сейчас ты завязался на знание о том, как работает диалог, что не есть гуд

2024-05-21 07:21 UTC, iljukhaput commented on src/core/management_layer/content/import/import_manager.cpp
> +                importDialog->hideDialog();
`isVisibleTo` сделал, но оно тоже возвращает false, если диалог был скрыт... Почему - так и не понял

2024-05-21 07:27 UTC, iljukhaput commented on src/core/management_layer/content/import/import_manager.cpp
> +                importDialog->hideDialog();
посмотрел в экспортерах - там `isVisibleTo` используется для экспорта синопсиса, но её вызов происходит при видимом диалоге. А если сделать вызов после скрытия диалога, то тоже вернулся бы `false`

2024-05-21 13:53 UTC, dimkanovikov commented on src/core/management_layer/content/import/import_manager.cpp
> +                importDialog->hideDialog();
хммм... сомнительно, но окей) заведу задачку на будущее - это поправить

2024-05-22 14:07 UTC, iljukhaput commented
перезалил

2024-05-22 14:59 UTC, iljukhaput commented
не упала)

2024-05-22 15:51 UTC, merged