Abstract markdown importer for novels and screenplays
story-apps/starc pull request #242
Opened 2024-05-23 12:36 UTC by iljukhaput

2024-05-27 03:32 UTC, dimkanovikov requested changes
проверил, с многострочными комментариями тоже работает?

2024-05-27 03:32 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.h
> +#include <QPair>
лучше использовать такую штуку `#include <QtContainerFwd>`, когда нужно добавить объявления контейнеров, но в то же время, чтобы не инклудить их

2024-05-27 03:32 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    for (QString str : QString(_screenplayText).remove('\r').split("\n")) {
я бы ещё сделал `for (const auto&  str`

2024-05-27 03:32 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +                paragraphText.chop(3);
тут типа `TO:` отрезается? предлагаю этого не делать, а брать текст целиком

2024-05-27 03:32 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.h
> +class CORE_LIBRARY_EXPORT ScreenplayFountainImporter : public ScreenplayAbstractImporter,
Что я понял - что название класса должно быть либо `AbstractScreenplayImporter`, либо просто `ScreenplayImporter`, но точно не посередине слово `Abstract`

2024-05-30 09:33 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_markdown_importer.h
> +#include <QPair>
сделал

2024-05-30 09:34 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    for (QString str : QString(_screenplayText).remove('\r').split("\n")) {
исправил

2024-05-30 09:34 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +                paragraphText.chop(3);
исправил

2024-05-30 09:34 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.h
> +class CORE_LIBRARY_EXPORT ScreenplayFountainImporter : public ScreenplayAbstractImporter,
исправил

2024-06-03 04:35 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +            _writer.writeAttribute(type.attribute, "true");
сейчас получается, что каждый формат будет записан отдельно, даже если у разных форматов единый текст, хотелось бы не делать так и для единых кусков текста писать форматирование единым проходом

2024-06-03 04:35 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    for (QString str : QString(_screenplayText).remove('\r').split("\n")) {
сорян, я тут натупил, там ниже строка изменяется... поэтому давай лучше просто `auto str` оставим

2024-06-03 04:40 UTC, dimkanovikov requested changes

2024-06-03 04:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    for (auto& str : scriptText.split("\n")) {
думаю тут уместней будет просто `auto str`, чтобы не поиметь проблем со ссылками на элементы временного списка в разных системах

2024-06-03 04:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    for (auto& str : scriptText.split("\n")) {
либо, как сделано ниже, сразу удалять `\r` и сделать её тут константой

2024-06-05 18:21 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +            _writer.writeAttribute(type.attribute, "true");
исправил

2024-06-05 18:22 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    for (auto& str : scriptText.split("\n")) {
исправил

2024-06-07 02:51 UTC, dimkanovikov requested changes

2024-06-07 02:51 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +    int position;
тут нужно дефолтное значение

2024-06-07 02:51 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +        const auto first = selectionTypes.first();
у вектора есть такие методы `constFirst` & `constLast`

2024-06-07 02:51 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +        SelectionTypeInText type
const

2024-06-07 02:51 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +        const auto first = selectionTypes.first();
либо тут можно делать через `takeFirst`, чтобы потом не заморачиваться с удалением

2024-06-07 02:51 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +              [](const SelectionTypeInText& type1, const SelectionTypeInText& type2) {
в компараторах или операторах в классе переменные по-классике именуют `lhs` & `rhs`, в нашем случае `_lhs` & `_rhs` :)

2024-06-07 03:52 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +              [](const SelectionTypeInText& type1, const SelectionTypeInText& type2) {
исправил

2024-06-07 03:53 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +        SelectionTypeInText type
исправил

2024-06-07 03:53 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +        const auto first = selectionTypes.first();
исправил

2024-06-07 03:53 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_markdown_importer.cpp
> +    int position;
исправил

2024-06-07 03:53 UTC, iljukhaput commented
С многострочными комментариями работает - проверил

2024-06-10 11:16 UTC, merged