Counters for stageplays, comicbooks and audioplays
story-apps/starc pull request #244
Opened 2024-05-29 11:57 UTC by iljukhaput

Add counters of pages, scenes (or panels for comicbooks), etc. Also add counting scenes for novels

2024-05-29 12:00 UTC, iljukhaput commented
Помимо новых счетчиков добавил ещё подсчет сцен для романа. Сам счетчик под это был, но показывал всегда ноль

2024-05-29 12:05 UTC, iljukhaput commented
Сейчас тут один нюанс есть, с которым пока не разобрался: в комиксе, когда создается новый блок текста с типом "Персонаж", счетчик сцен уменьшается на единицу. Но если после этого ввести хотя бы один символ, снова пересчитывается на правильное количество

2024-05-30 04:29 UTC, dimkanovikov requested changes

2024-05-30 04:29 UTC, dimkanovikov commented on src/corelib/business_layer/model/novel/text/novel_text_model.cpp
> +                updateChildNumbering(childItem);
тут два момента
1. у сцены не может быть вложенной сцены, поэтому тут можно детей не проверять
2. группой также может быть и бит, поэтому нужно удостовериться, что это точно сцена

2024-05-30 04:29 UTC, dimkanovikov commented on src/corelib/business_layer/model/stageplay/text/stageplay_text_model_text_item.h
Слушай, если нам нужен этот функционал везде теперь, почему бы его не добавить в `TextModelTextItem`?

2024-05-31 06:34 UTC, iljukhaput commented on src/corelib/business_layer/model/novel/text/novel_text_model.cpp
> +                updateChildNumbering(childItem);
исправил

2024-05-31 06:35 UTC, iljukhaput commented on src/corelib/business_layer/model/stageplay/text/stageplay_text_model_text_item.h
вынес даже выше - в `TextModelItem`

2024-05-31 06:41 UTC, iljukhaput commented
проблему со счетчиком панелей в комиксе тоже поправил
как именно она происходила до конца не понял, но решилось тем, что перенес инкрементацию счетчика перед рекурсивным вызовом `updateChildNumbering(childItem)` в `ComicBookTextModel::Implementation::updateNumbering()`

2024-06-03 03:01 UTC, dimkanovikov commented on src/core/management_layer/plugins/audioplay_text_structure/ui/audioplay_text_structure_view.cpp
> +        connect(d->model, &BusinessLayer::AudioplayTextModel::modelReset, this,
тут что-то странное у нас происходит - кастим в один тип, потом в коннекшенах используем другой) работает только потому что это сигналы вообще базового класса))) надо исправить сигналы на `&QSortFilterModel::modelReset` и т.п.

2024-06-03 03:03 UTC, dimkanovikov commented on src/core/management_layer/plugins/comic_book_text_structure/ui/comic_book_text_structure_view.cpp
тут аналогично предыдущему (вьюхе структуры аудиопостановки)

2024-06-03 03:03 UTC, dimkanovikov commented on src/core/management_layer/plugins/stageplay_text_structure/ui/stageplay_text_structure_view.cpp
ну и тут тоже аналогично предыдущему (вьюхе структуры аудиопостановки)

2024-06-03 03:09 UTC, dimkanovikov commented on src/corelib/business_layer/model/audioplay/text/audioplay_text_model.cpp
> +                                                                bool _force)
не понял на что тут параметр `_force` влияет?

2024-06-03 03:12 UTC, dimkanovikov commented on src/corelib/business_layer/model/audioplay/text/audioplay_text_model_folder_item.h
> +#include <QPair>
можно выкинуть это изменение

2024-06-03 03:18 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.h
> +     * @brief Обновляем хронометраж, при изменении текста
тогда уже счётчики)

2024-06-03 03:19 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
предлагаю не делать этого в базовой имплементации, а только в конкретных наследниках - тут пусть считается максимально тупо

2024-06-03 03:21 UTC, dimkanovikov commented on src/corelib/business_layer/model/stageplay/text/stageplay_text_model_folder_item.h
> +#include <QPair>
выкинуть надо

2024-06-03 03:27 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
либо добавить в интерфейс метод, который будет говорить нужно ли считать для этого типа параграфа счётчики и его использовать в наследниках

2024-06-03 03:28 UTC, dimkanovikov commented on src/corelib/business_layer/model/comic_book/text/comic_book_text_model_panel_item.h
> +#include <corelib/business_layer/model/text/text_model_group_item.h>
не понял зачем это?

2024-06-03 03:28 UTC, dimkanovikov commented on src/corelib/business_layer/model/comic_book/text/comic_book_text_model_page_item.h
> +#include <corelib/business_layer/model/text/text_model_group_item.h>
это тоже зачем?

2024-06-03 07:26 UTC, iljukhaput commented on src/core/management_layer/plugins/audioplay_text_structure/ui/audioplay_text_structure_view.cpp
> +            const bool kCanChangeModel = false;
исправил

2024-06-03 07:27 UTC, iljukhaput commented on src/core/management_layer/plugins/audioplay_text_structure/ui/audioplay_text_structure_view.cpp
> +        connect(d->model, &BusinessLayer::AudioplayTextModel::modelReset, this,
исправил

2024-06-03 07:27 UTC, iljukhaput commented on src/core/management_layer/plugins/comic_book_text_structure/ui/comic_book_text_structure_view.cpp
и тут исправил

2024-06-03 07:27 UTC, iljukhaput commented on src/core/management_layer/plugins/stageplay_text_structure/ui/stageplay_text_structure_view.cpp
и тут тоже исправил

2024-06-03 07:32 UTC, iljukhaput commented on src/corelib/business_layer/model/audioplay/text/audioplay_text_model.cpp
> +                                                                bool _force)
тут забыл передать этот параметр дальше в `textItem->updateCounters()`

2024-06-03 07:32 UTC, iljukhaput commented on src/corelib/business_layer/model/audioplay/text/audioplay_text_model_folder_item.h
> +#include <QPair>
выкинул

2024-06-03 07:32 UTC, iljukhaput commented on src/corelib/business_layer/model/text/text_model_text_item.h
> +     * @brief Обновляем хронометраж, при изменении текста
исправил тут и в остальных местах тоже

2024-06-03 07:38 UTC, iljukhaput commented on src/corelib/business_layer/model/stageplay/text/stageplay_text_model_folder_item.h
> +#include <QPair>
выкинул

2024-06-03 07:39 UTC, iljukhaput commented on src/corelib/business_layer/model/comic_book/text/comic_book_text_model_panel_item.h
> +#include <corelib/business_layer/model/text/text_model_group_item.h>
это случайно получилось, исправил

2024-06-03 07:39 UTC, iljukhaput commented on src/corelib/business_layer/model/comic_book/text/comic_book_text_model_page_item.h
> +#include <corelib/business_layer/model/text/text_model_group_item.h>
тут тоже случайно получилось, исправил

2024-06-03 08:34 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
супер, только это актуально для романа тоже 

плюс, предлагаю сразу сделать момент, что биты не учитываются в тексте сценария/романа, а в поэпизоднике/плане учитываются, но не учитываются другие форматы. Это сейчас можно будет реализовать добавлением условий при пересчёте счётчиков?

2024-06-03 10:05 UTC, iljukhaput commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
да, можно, сделал)
плюс ещё понял, что в аудиопьесах не нужно биты отсеивать

2024-06-03 10:23 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
а ты проверил?) оно реально работает через `model()->document()->type() != Domain::DocumentObjectType::NovelOutline`? там с этими алиасами хитро как-то было, возможно лучше будет использовать методы типа `NovelTextDocument::isOutlineDocument`

2024-06-03 13:07 UTC, iljukhaput commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
да, я поспешил с выводами, оно не работает так...
тогда не получится просто развести на текст/план, чтоб отсеивать другие типы блоков, по крайней мере я что-то не могу придумать, как здесь получить объект класса `NovelTextDocument`

2024-06-03 13:14 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
ага, давай тогда не считать биты и заведу задачку на подумать

2024-06-03 13:22 UTC, iljukhaput commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
сделал

2024-06-03 13:23 UTC, iljukhaput commented on src/corelib/business_layer/model/novel/text/novel_text_model_text_item.cpp
> +        QSet<TextParagraphType> accountingBlock = {
этого, соответственно, больше нет

2024-06-03 13:57 UTC, dimkanovikov commented on src/corelib/business_layer/model/text/text_model_text_item.cpp
> +    //
в романах биты нужно тоже пропускать

2024-06-04 09:59 UTC, merged