Abstract fountain importer
story-apps/starc pull request #250
Opened 2024-06-11 17:31 UTC by iljukhaput

2024-06-12 04:23 UTC, dimkanovikov requested changes

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        d->processNotes(paragraphText, blockType, writer);
предлагаю старое название оставить - тут всё таки не только заметки обрабатываются, но блок целиком (а то кажется ты сам мальца подзапутался, о чём ~~врёт~~ говорит комментарий выше)

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
а почему ты добавлял в каждый `case` эту проверку, а не сделал это после свитча, когда у нас финально определился тип блока?

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            } else if (paragraphText.startsWith("Music: ")) {
вот такие штуки, хотелось бы в наследнике видеть, т.к. это наше придуманное расширение формата фонтана

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/audioplay/audioplay_fountain_importer.cpp
> +            _writer.writeAttribute(xml::kTypeAttribute, "start");
в таком кейсе нужно записать пустое имя персонажа в первую колонку, чтобы реплика вставла во вторую

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/audioplay/audioplay_fountain_importer.cpp
> +        if (!d->splitterIsOpen) {
ещё тут есть момент - мы используем расположение реплик в таблице, если задан соответствующий параметр текущего шаблона (`TextTemplate::placeDialoguesInTable`) - нужно добавить эту проверку

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.h
> +    virtual bool appendBlockInInheritor(const QString& _paragraphText, TextParagraphType _type,
предлагаю этот метод чутка переделать `void writeBlock...`

в реализации абстрактного класса поместить весь код, который сейчас у нас свёрнут внутри проверки не был ли блок добавлен в наследнике

а в реализации наследника делать что-то типа

```c++
switch (_type) {
case Character: {
    // обработка
    break;
}
default: {
    AbstractFountainImporter::writeBlock();
    break;
}
```

2024-06-12 04:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.h
> +    virtual void postProcessPrevBlock(TextParagraphType _type, QXmlStreamWriter& _writer) const;
давай целиком напишем `Previous`, в названиях методов лучше не сокращать

2024-06-13 07:22 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.h
> +    virtual QString character(const QString& _text) const = 0;
добавил

2024-06-13 07:23 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +void ProjectManager::setCurrentDocumentExportAvailable(bool _available)
перенес этот и ещё пару методов для полной синхронизации

2024-06-13 07:24 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->projectStructureModel->appendItem(synopsisItem, novelItem, {});
у них так не получится, насколько я понимаю
там ниже используется этот указатель на синопсис при вставке плана и поэпизодника

2024-06-13 07:25 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            const bool shouldClosePrevBlock = !isFirstBlock;
исправил

2024-06-13 07:25 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        d->processNotes(paragraphText, blockType, writer);
исправил

2024-06-13 07:26 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        QCoreApplication::translate("BusinessLayer::FountainImporter", "INT"),
а стоит здесь поменять контекст на `"BusinessLayer::AbstractFountainImporter"`? 
и вообще по какому принципу мы задаем контекст для переводов?
это не всегда просто имя класса?

2024-06-13 07:35 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
тут поправил два момента:
1. в этой ветке перенес проверку на строчку ниже, после перезаписи типа блока
2. добавил проверку после каждой перезаписи типа блока (сначала не стал её делать после тех блоков, которые есть в каждом документе: сцена, персонаж, заметка по тексту и диалог)

но не совсем понял, где финально определяется тип блока?  после свича же сразу отправляется на обработку блок

2024-06-13 07:45 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            } else if (paragraphText.startsWith("Music: ")) {
перенес в `AudioplayFountainImporter::writeBlock`
правда смущает немного что это метод, который записывает, а теперь в нем немного обработки есть...
это ок или не ок?)

2024-06-13 07:53 UTC, iljukhaput commented on src/corelib/business_layer/import/audioplay/audioplay_fountain_importer.cpp
> +            _writer.writeAttribute(xml::kTypeAttribute, "start");
исправил

2024-06-13 07:55 UTC, iljukhaput commented on src/corelib/business_layer/import/audioplay/audioplay_fountain_importer.cpp
> +        if (!d->splitterIsOpen) {
сделал

2024-06-13 08:00 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.h
> +    virtual bool appendBlockInInheritor(const QString& _paragraphText, TextParagraphType _type,
сделал

2024-06-13 08:00 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.h
> +    virtual void postProcessPrevBlock(TextParagraphType _type, QXmlStreamWriter& _writer) const;
сделал

2024-06-13 08:26 UTC, iljukhaput commented
ещё раз поправил запись пустого персонажа (:

2024-06-14 08:26 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        QCoreApplication::translate("BusinessLayer::FountainImporter", "INT"),
да, контекст нужно поменять - обычно это и должно быть имя класса (в нашем подходе)

2024-06-14 08:28 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    writer.writeEndElement();
полагаю, что тут ещё тоже нужно сделать постобработку для самого последнего блока

2024-06-14 08:38 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
в свитче и определяется, тут есть единственное исключение - это заголовки, которые мы интерпретируем как секвенции, там эта проверка выглядит уместной (единственный там момент, видимо нужно в интерфейсе определить пару методов, которые будут возвращать типы начала и конца папки, для сценариев это будут секвенции, для романов главы), в остальных случаях не надо делать её в каждой ветке, а надо вынести её перед обработкой - типа если этот блок можем интерпретировать, то обрабатываем, а в противном случае, я бы предложил его интерпретировать, как дефолтный тип, чтобы не терять блоки текста при импорте

2024-06-14 08:42 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            } else if (paragraphText.startsWith("Music: ")) {
это не ок, хер вспомним потом, почему у нас некоторые блоки превращаются в музыку, а некоторые нет) надо как-то более явно это сделать

2024-06-14 08:45 UTC, dimkanovikov commented on src/corelib/business_layer/import/audioplay/audioplay_fountain_importer.cpp
> +    return _text;
тут нужно использовать `AudioplayCharacterParser`

2024-06-17 04:55 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
а романы мы вообще будем импортировать из фонтана?
сейчас их только из маркдауна можем, для этого отдельный класс `AbstractMarkdownImporter`

2024-06-17 05:23 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
Всё верно, не будем, там только маркдаун

2024-06-17 05:37 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
А нужен ли в таком случае дополнительный интерфейс для определения типа папки?
Из фонтана мы импортируем только в сценарии, комиксы, пьесы и аудипьесы. При этом папки есть только в сценарии

2024-06-17 05:38 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (!d->possibleBlockTypes.contains(blockType)) {
нет, всё это будут секвенции

2024-06-17 08:29 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        QCoreApplication::translate("BusinessLayer::FountainImporter", "INT"),
поменял

2024-06-17 08:37 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            } else if (paragraphText.startsWith("Music: ")) {
сделал виртуальный метод` TextParagraphType blockType(QString& _paragraphText)`, где определяется тип блока

2024-06-17 08:38 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    writer.writeEndElement();
да, точно, сделал

2024-06-17 08:38 UTC, iljukhaput commented on src/corelib/business_layer/import/audioplay/audioplay_fountain_importer.cpp
> +    return _text;
исправил

2024-06-17 10:55 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        // Либо бит, либо PageBreak. Обработаем отдельно, т.к. PageBreak у нас сейчас нет
Давай сделаем обработку, мы же можем проверить, что следующий символ не `=` и тогда это точно бит, а в обработке оставим только кейс с `===`

2024-06-17 11:16 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        // Либо бит, либо PageBreak. Обработаем отдельно, т.к. PageBreak у нас сейчас нет
исправил

2024-06-17 11:20 UTC, iljukhaput commented
Если правок больше не будет, то буду делать импорт в пьесы и комиксы

2024-06-18 11:28 UTC, iljukhaput commented
сделал ещё сохранение настроек диалога

2024-06-18 11:32 UTC, iljukhaput commented
и пару вопросов: 
в xml-структуре документов есть атрибут `plots` у тегов страниц, кадров и др.
например `<page uuid="{dd62f32a-2d33-4f1a-85b8-eb774c6c06cc}" plots="" >`

Но сейчас при импорте он не пишется.
Нужно его писать? И можешь немного пояснить для чего он?

2024-06-18 11:48 UTC, dimkanovikov commented
> и пару вопросов: в xml-структуре документов есть атрибут `plots` у тегов страниц, кадров и др. например `<page uuid="{dd62f32a-2d33-4f1a-85b8-eb774c6c06cc}" plots="" >`
> 
> Но сейчас при импорте он не пишется. Нужно его писать? И можешь немного пояснить для чего он?

Пока никак не используется нигде. По плану туда будут добавляться сюжетные линии каким-то образом. Но пока он нигде не используется и из фонтана мы его точно не вытащим, поэтому можно забить.

2024-06-18 15:18 UTC, dimkanovikov requested changes

2024-06-18 15:18 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            // проходит, хотя это не титульная страница
давай тогда добавим проверку на допустимые ключи титульной страницы

2024-06-18 15:18 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        createItem(DocumentObjectType::ComicBookText, tr("ComicBook")), comicbookItem,
`tr("Comic book")`

2024-06-18 15:18 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +    importLocations->setChecked(settings.value(kImportLocations, false).toBool());
предлагаю персонажей и локации включить по-умолчанию

2024-06-18 15:18 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +        case Domain::DocumentObjectType::Stageplay: {
предлагаю добавить комиксы тоже - мы в них не можем локации импортировать, плюс поставить их вместе с подкастами и пьесами в один блок и не создавать три одинаковых кейса

2024-06-18 15:18 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +    QSettings settings;
что-то тут настройки как будто не в том месте загружаются... тут же надо скорей проверять, остался ли необходимый тип документа в выпадающем списке и оставлять его активным

2024-06-18 15:18 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.h
> +    BusinessLayer::StageplayImportOptions stageplayImportOptions() const;
а для комиксов?

2024-06-18 15:18 UTC, dimkanovikov commented on src/corelib/business_layer/import/comic_book/comic_book_plain_text_importer.h
я думаю, что это можно выкинуть, оно по-сути заменяется импортером фонтан формата

2024-06-19 10:52 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        if (isFirstLine) {
тут тоже надо скорректировать обработку

2024-06-19 10:52 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +                    isTitle = true;
тут предлагаю сделать проверку только для начала строки, плюс, если мы нашли совпадение, то сразу делать завершать обработку

2024-06-19 10:52 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            // проходит, хотя это не титульная страница
нет, не нужно его дополнительно никак обрабатывать

2024-06-19 10:53 UTC, dimkanovikov commented on src/core/ui/import/import_dialog.cpp
> +        case Domain::DocumentObjectType::Stageplay: {
Предлагаю его оставить вообще только для сценариев, на его обработку заведу отдельную задачу

2024-06-19 11:49 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +                    isTitle = true;
сделал

2024-06-19 11:49 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        if (isFirstLine) {
сделал

2024-06-19 11:50 UTC, iljukhaput commented on src/core/ui/import/import_dialog.cpp
> +        case Domain::DocumentObjectType::Stageplay: {
сделал
при этом отдельные классы для настроек импорта подкастов и пьес стали не нужны, удалил их

2024-06-19 11:53 UTC, merged