Double dialogues import
story-apps/starc pull request #251
Opened 2024-06-19 08:33 UTC by iljukhaput

2024-06-19 08:46 UTC, iljukhaput commented
Сделал в абстрактном классе - в итоге будет работать не только для сценариев, а и для других документов тоже, если в них не будет установлена запись диалога в таблицу

Плюс вынес в абстрактный класс запись диалога в таблицу и добавил двоеточие к имени персонажа при записи в таблицу

2024-06-19 12:53 UTC, iljukhaput commented
перезалил после ребейза

2024-06-20 08:19 UTC, dimkanovikov requested changes

2024-06-20 08:19 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    return TemplatesFacade::screenplayTemplate().placeDialoguesInTable();
по идее для сценариев это не актуально, предлагаю тут всегда false возвращать

2024-06-20 08:19 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
>                      paragraphText.chop(1);
тут нужно не только последний символ убрать, но и всё пространство, в доке фонтана так написано `Any number of spaces between the Character name and the caret are acceptable, and will be ignored. All that matters is that the caret is the last character on the line.`

2024-06-20 08:19 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        // строка и персонаж) и третий параграф помечен как двойной диалог
этот алгоритм сломается на кейсе

```
ДИМА
(весело)
Привет, пупсики.

ИЛЬЯ ^
Как?
```

Я думаю, что теоретически там может быть много строк в первой реплике, скорее нужно бежать до пустой строки и смотреть если следующая заканчивается символом двойного диалога.

2024-06-20 08:19 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        }
зачем тут это всё делать, если мы это уже делаем в момент обработки самого текста блока, перед тем, как его записать в xml?

2024-06-20 08:19 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        else if (d->isDoubleDialogue) {
не вижу, чтобы этот флаг сбрасывался где-то

2024-06-20 08:19 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +                d->shouldToCloseSplitter = true;
после реплики ещё может идти ремарка, потом другая реплика и т.п.

2024-06-21 05:22 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +    return TemplatesFacade::screenplayTemplate().placeDialoguesInTable();
сделал

2024-06-21 05:22 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
>                      paragraphText.chop(1);
исправил

2024-06-21 05:23 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        // строка и персонаж) и третий параграф помечен как двойной диалог
исправил

2024-06-21 05:24 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        else if (d->isDoubleDialogue) {
исправил

2024-06-21 05:24 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +                d->shouldToCloseSplitter = true;
исправил

2024-06-21 05:28 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +        }
исправил
сделал по аналогии с обработкой сцен (то что мы в прошлом пр обсуждали)

2024-06-21 05:38 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (currentBlockType == TextParagraphType::Parenthetical && placeDialoguesInTable()) {
для подобных кейсов, если импортируем в пьесу, например:
```
ПЕРСОНАЖ 
(ремарка)
Реплика
```
то есть в пьесе у нас ремарок нет, она назначается типом по умолчанию и сбивает форматирование при записи в таблицу

Ещё как вариант, мне кажется, можно сохранять текст ремарки в буфер, писать реплику, а после уже ремарку в виде дефолтного типа. Но стоит ли так заморачиваться?

2024-06-23 06:03 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (currentBlockType == TextParagraphType::Parenthetical && placeDialoguesInTable()) {
я подумаю - вообще у нас просили добавить ремарки в пьесы (хоть там и нет чёткого формата - все извращаются как только могут), вернусь по этому моменту

2024-06-24 03:40 UTC, dimkanovikov requested changes

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +#include <business_layer/templates/templates_facade.h>
нужны тут ещё эти инклуды? все?

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    void postProcessBlock(QXmlStreamWriter& _writer, TextParagraphType _currentBlockType);
по-хорошему первыми должны идти входные (неизменяемые) параметры, а следом выходные (которые могут быть изменены)

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (_currentBlockType != TextParagraphType::Dialogue) {
тут предлагаю тоже допускать ремарки и реплики

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (currentBlockType == TextParagraphType::Parenthetical && placeDialoguesInTable()) {
давай ремарки, если они недоступны, рассматривать как реплики

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            // ... если персонаж, удалим обозначение двойного диалога и добавим двоеточие
я бы тут комментарий разделил на два, двоеточие добавляется ниже и там же видно, что оно не обязательно, а сейчас читается как будто это делается всегдя

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    void postProcessBlock(QXmlStreamWriter& _writer, TextParagraphType _currentBlockType);
и ещё заметил, что ты убрал слово `previous` и теперь кажется будто бы это постобработка текущего блока, хотя по факту это не так, предлагаю вернуть

2024-06-24 03:40 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    if (!d->splitterIsOpen && d->isDoubleDialogue) {
тут предлагаю местами поменять условия, т.к. в 99% случаев первое будет истинно, а второе нет, лучше бы писать условия так, чтобы они как можно скорей завершались

2024-06-24 04:43 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (currentBlockType == TextParagraphType::Parenthetical && placeDialoguesInTable()) {
сделал
при этом удаление скобок у ремарки перенес ниже, чтобы, если будем считать репликой, скобки остались

2024-06-24 04:43 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_fountain_importer.cpp
> +#include <business_layer/templates/templates_facade.h>
удалил ненужные

2024-06-24 04:44 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    void postProcessBlock(QXmlStreamWriter& _writer, TextParagraphType _currentBlockType);
`previous` вернул, параметры местами поменял

2024-06-24 04:45 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (_currentBlockType != TextParagraphType::Dialogue) {
сделал

2024-06-24 04:45 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            // ... если персонаж, удалим обозначение двойного диалога и добавим двоеточие
исправил

2024-06-24 04:45 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +    if (!d->splitterIsOpen && d->isDoubleDialogue) {
исправил

2024-06-25 07:56 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_fountain_importer.cpp
> +            if (currentBlockType == TextParagraphType::Parenthetical && placeDialoguesInTable()) {
сделал

2024-06-25 08:25 UTC, dimkanovikov approved these changes

2024-06-25 08:25 UTC, merged