Abstract QTextDocument importer
story-apps/starc pull request #264
Opened 2024-09-02 06:54 UTC by iljukhaput

2024-09-02 10:43 UTC, iljukhaput commented
перезалил - перенес часть методов в протектед часть

2024-09-06 04:03 UTC, dimkanovikov commented
влил импорт пдф, теперь опять нужно отребейзить реквесты

2024-09-06 04:05 UTC, iljukhaput commented
> влил импорт пдф, теперь опять нужно отребейзить реквесты

сейчас сделаю
а вообще, так и должно быть или я как-то неправильно заливаю пр, что приходится ребейзить?

2024-09-06 04:11 UTC, dimkanovikov commented
да, это нормально, т.к. ты делаешь реквест в мастер, то в него включаются все коммиты, когда один из них попадает туда, то получается такая ситуация с другим

2024-09-06 04:13 UTC, iljukhaput commented
перезалил

2024-09-06 05:01 UTC, dimkanovikov requested changes

2024-09-06 05:01 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +    virtual QString processSceneHeading(const ImportOptions& _options, QTextCursor& _cursor) const;
Тут суть функции же в том, чтобы извлечь номер сцены из заголовка? давай так её и назовём

2024-09-06 05:08 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_pdf_importer.cpp
> -            // Пишем редакторские комментарии
думаю что да, но наверняка - сказать пока не могу, надо в спеке покопаться
чуть попозже отпишу по этому поводу

2024-09-06 05:14 UTC, dimkanovikov commented on src/corelib/business_layer/import/screenplay/screenplay_pdf_importer.cpp
> -            // Пишем редакторские комментарии
окей, давай это вынесем тогда в отдельную задачку тоже, заведи плиз эту и ту из соседнего реквеста с подробностями на следующий спринт

2024-09-06 05:16 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +class CORE_LIBRARY_EXPORT AbstractQTextDocumentImporter
у нас ещё есть класс `ScreenplayDocumentImporter`, который из docx импортирует
может его тогда переименуем в `ScreenplayDocxImporter`, например?

чтобы не было, что AbstractDocumentImporter - из QTextDocument
а ScreenplayDocumentImporter -  из docx

2024-09-06 05:54 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +class CORE_LIBRARY_EXPORT AbstractQTextDocumentImporter
да, хорошая идея

2024-09-06 06:26 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +class CORE_LIBRARY_EXPORT AbstractQTextDocumentImporter
сделал

2024-09-06 06:27 UTC, iljukhaput commented on src/corelib/business_layer/import/screenplay/screenplay_pdf_importer.cpp
> -            // Пишем редакторские комментарии
задачи завел

2024-09-06 06:29 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +    TextParagraphType typeForTextCursor(const QTextCursor& _cursor,
поднял
а вообще, есть у нас какое-то четкое правило по группировке методов?)
я просто по алфавиту расположил, но, так понимаю, как минимум виртуальность стоит учитывать

2024-09-06 06:29 UTC, iljukhaput commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +    virtual QString processSceneHeading(const ImportOptions& _options, QTextCursor& _cursor) const;
переименовал

2024-09-06 07:09 UTC, dimkanovikov commented on src/corelib/business_layer/import/abstract_qtextdocument_importer.h
> +    TextParagraphType typeForTextCursor(const QTextCursor& _cursor,
Какого-то чёткого правила нет и на виртуальности завязки тоже нет, скорее общее правило от общего к частному. Типа сначала более универсальные методы, а потом более специализированные под конкретные кейсы

2024-09-06 07:23 UTC, merged