Refactor export dialogs
story-apps/starc pull request #269
Opened 2024-09-12 15:26 UTC by iljukhaput

2024-09-12 15:37 UTC, iljukhaput commented
добавил моментик небольшой ещё: если при экспорте документов не выбрано ни одного документа, то кнопка экспорта становится неактивной

2024-09-12 16:43 UTC, iljukhaput commented
так, сборка не прошла под линукс
завтра попробую либо конструктор прописать, либо каждое поле отдельно скопировать, если получше варианта не найдется)

2024-09-13 09:26 UTC, iljukhaput commented
ещё один момент небольшой:
в диалогах экспорта текстовых документов чекбокс "Script" (он же "Screenplay" у сценариев и "Novel" у романов) заменил на общий для всех "Text"

2024-09-13 11:48 UTC, dimkanovikov requested changes

2024-09-13 11:48 UTC, dimkanovikov commented on src/core/ui/export/script_export_dialog.h
> +    virtual bool showRightLayout() const;
лучше isRightLayoutVisible или как-то так, а то выглядит как метод, который что-то показывает

2024-09-13 11:48 UTC, dimkanovikov commented on src/core/ui/export/script_export_dialog.h
> +    virtual void includeScriptChanged(bool _checked) const;
а тут что-то типа `processIncludeTextChanged`

2024-09-13 11:48 UTC, dimkanovikov commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
вот тут нельзя отдавать сразу нужные параметры тоже из-за проблем с компиляцией? или ты специально их развёл?

2024-09-13 11:48 UTC, dimkanovikov commented on src/core/ui/export/abstract_export_dialog.h
> +enum class ContentLayouts {
вот это зачем нужно не понял?

2024-09-13 13:12 UTC, iljukhaput commented on src/core/ui/export/stageplay_export_dialog.cpp
> -const QString kIncludeTitlePageKey = kGroupKey + "include-title-page";
я думал так даже лучше будет)
например, пользователь экспортировал один документ с определенными настройками, потом хочет экспортировать сразу другой, а у него общие для документов настройки сохранились

но если это менее популярный сценарий, то переделаю сейчас

2024-09-13 13:14 UTC, iljukhaput commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
я специально их развел, т.к. потомки возвращают опции своего типа (`AudioplayExportOptions` и т.п.)
(здесь только ошибочно этот метод в паблик части - перенес в протектед)

2024-09-13 14:25 UTC, iljukhaput commented on src/corelib/business_layer/export/documents_export_options.h
> +struct CORE_LIBRARY_EXPORT DocumentsExportOptions : public ExportOptions {
Может быть "Элементы" или "Элементы произведения"?

2024-09-13 14:49 UTC, iljukhaput commented on src/core/ui/export/abstract_export_dialog.h
> +    explicit AbstractExportDialog(QList<BusinessLayer::ExportFileFormat> _formats,
исправил

2024-09-13 14:53 UTC, iljukhaput commented on src/corelib/business_layer/export/export_options.h
> +    static void copy(const ExportOptions* _source, ExportOptions* _dest);
да, действительно, с конструктором поаккуратней смотрится
исправил, но в конструкторе использовал эту же функцию, чтобы не копипастить

вопрос только: стоит ли заинлайнить конструкторы? а то там одна строчка, а создавать cpp-файлы пришлось для каждого класса опций

2024-09-13 14:54 UTC, iljukhaput commented on src/corelib/business_layer/export/documents_export_options.h
> +struct CORE_LIBRARY_EXPORT DocumentsExportOptions : public ExportOptions {
Описания добавил, а "документы" пока не переименовывал

2024-09-13 14:54 UTC, iljukhaput commented on src/core/ui/export/script_export_dialog.h
> +    virtual bool showRightLayout() const;
исправил

2024-09-13 14:55 UTC, iljukhaput commented on src/core/ui/export/script_export_dialog.h
> +    virtual void includeScriptChanged(bool _checked) const;
исправил

2024-09-13 14:56 UTC, iljukhaput commented on src/core/ui/export/abstract_export_dialog.h
> +enum class ContentLayouts {
это случайно проглядел остатки чернового варианта
убрал

2024-09-15 12:52 UTC, dimkanovikov commented on src/corelib/business_layer/export/export_options.h
> +    static void copy(const ExportOptions* _source, ExportOptions* _dest);
да, вполне можно заинлайнить

2024-09-15 12:53 UTC, dimkanovikov commented on src/corelib/business_layer/export/documents_export_options.h
> +struct CORE_LIBRARY_EXPORT DocumentsExportOptions : public ExportOptions {
Может быть что-то типа `WorldItem`?

2024-09-15 12:58 UTC, dimkanovikov commented on src/core/ui/export/stageplay_export_dialog.cpp
> -const QString kIncludeTitlePageKey = kGroupKey + "include-title-page";
Не не, такого нет кейса, чтобы они экпортировали разные документы, то один, то другой... Тут обычно чел работает над проектом и в какой-то момент экспортит, дорабатывает - экспортит. Но в какой-то момент может вернуться к другому документу, поработать с ним и экспортнуть опять. Хотя в этом кейсе вроде тоже норм получается... Может нам вообще подокументно сохранять параметры экспорта?

2024-09-15 12:59 UTC, dimkanovikov commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
А можешь объяснить задумку?

2024-09-15 14:59 UTC, iljukhaput commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
Если я правильно понимаю, вопрос в том, почему этот метод возвращает `ExportOptions`, а не его наследников (`AudioplayExportOptions` и т.п.)

`ScriptExportDialog` - это базовый класс для `AudioplayExportDialog`, `ComicBookExportDialog` и т.д. 
В нем есть параметры только общие для наследников. 
Наследники получают из этого метода `ExportOptions`, копируют их в свои `AudioplayExportOptions`, `ComicBookExportOptions` и т.п. 
И дозаполняют их в соответствии со своими индивидуальными параметрами

2024-09-16 00:00 UTC, iljukhaput commented on src/corelib/business_layer/export/documents_export_options.h
> +struct CORE_LIBRARY_EXPORT DocumentsExportOptions : public ExportOptions {
а миры мы будет так экспортировать?
если да, то нормально, что тогда мир - это тоже `WorldItem`?

2024-09-16 03:42 UTC, dimkanovikov commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
Вопрос скорее в том, почему не оставить один метод?

2024-09-16 03:50 UTC, dimkanovikov commented on src/corelib/business_layer/export/documents_export_options.h
> +struct CORE_LIBRARY_EXPORT DocumentsExportOptions : public ExportOptions {
Да, миры тоже будем экспортировать. Ладно, пусть будет как сейчас. Если придумаем как лучше будет, то переименуем)

2024-09-16 03:52 UTC, iljukhaput commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
нам нужно получать значения разных типов, а перегрузка в этом случае не сработает

2024-09-16 04:35 UTC, dimkanovikov commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
мы же можем переопределить метод и скорректировать тип возвращаемого значения, такой вариант не подойдёт?

2024-09-16 09:17 UTC, dimkanovikov commented on src/core/ui/export/stageplay_export_dialog.cpp
> -const QString kIncludeTitlePageKey = kGroupKey + "include-title-page";
давай реально их сохранять к каждому конкретному документу

2024-09-16 09:18 UTC, iljukhaput commented on src/core/ui/export/stageplay_export_dialog.cpp
> -const QString kIncludeTitlePageKey = kGroupKey + "include-title-page";
уже сделал)

2024-09-16 10:51 UTC, iljukhaput commented on src/core/ui/export/script_export_dialog.h
> +    BusinessLayer::ExportOptions baseExportOptions() const override;
переделал

2024-09-16 10:51 UTC, iljukhaput commented on src/corelib/business_layer/export/documents_export_options.h
> +struct CORE_LIBRARY_EXPORT DocumentsExportOptions : public ExportOptions {
оставил как есть

2024-09-16 10:52 UTC, iljukhaput commented on src/corelib/business_layer/export/export_options.h
> +    static void copy(const ExportOptions* _source, ExportOptions* _dest);
сделал

2024-09-16 11:26 UTC, dimkanovikov commented on src/core/ui/export/stageplay_export_dialog.cpp
> +static const QList<BusinessLayer::ExportFileFormat> kStageplayExportFormats({
лучше использовать `QVector` по дефолту, если нет особых резонов использовать именно `QList`

2024-09-16 11:29 UTC, dimkanovikov commented on src/core/ui/export/stageplay_export_dialog.cpp
> +    setCurrentFileFormat(settings.value(groupModelKey + kFormatKey, 0).toInt());
я тут предлагаю сделать метод в `AbstractExportDialog` который будет принимать на вход строку, а возвращать ключ уже с юидом, и используя его, добавлять туда суффиксы нужные в дочерних классах получать ключи параметров

2024-09-16 12:29 UTC, iljukhaput commented on src/core/ui/export/stageplay_export_dialog.cpp
> +static const QList<BusinessLayer::ExportFileFormat> kStageplayExportFormats({
исправил

2024-09-16 12:29 UTC, iljukhaput commented on src/core/ui/export/stageplay_export_dialog.cpp
> +    setCurrentFileFormat(settings.value(groupModelKey + kFormatKey, 0).toInt());
сделал

2024-09-16 12:35 UTC, dimkanovikov commented on src/core/ui/export/stageplay_export_dialog.h
> +#include <ui/export/script_export_dialog.h>
теперь можно тут форварднуть объявление опции, раз у нас ссылка возвращается в методе

2024-09-16 12:40 UTC, iljukhaput commented on src/core/ui/export/stageplay_export_dialog.h
> +#include <ui/export/script_export_dialog.h>
компилятор говорит что нельзя, из-за того что мы оверрайдим

2024-09-16 12:59 UTC, dimkanovikov commented on src/core/ui/export/abstract_export_dialog.cpp
> +    return d->groupUuidKey + _parameterKey;
вот тут предлагаю сделать в таком виде формирование ключа

"widgets/export-dialog/" + UUID + "/" + PARAMETER

где PARAMETER будет задаваться извне в виде просто текстовых меток, типа "format" etc.

2024-09-16 15:38 UTC, iljukhaput commented on src/core/ui/export/abstract_export_dialog.cpp
> +    return d->groupUuidKey + _parameterKey;
сделал

2024-09-16 16:51 UTC, merged