Fix bug of updating the start page
story-apps/starc pull request #271
Opened 2024-09-20 15:26 UTC by iljukhaput

2024-09-20 15:30 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +                    1000, q, [this] { QApplication::postEvent(q, new DesignSystemChangeEvent); });
Единственное, мне не очень нравится здесь таймер на секунду...
Но как сделать лучше - пока так и не придумал

2024-09-23 09:18 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +                    1000, q, [this] { QApplication::postEvent(q, new DesignSystemChangeEvent); });
А зачем это делать? ЧТобы инфа о проекте обновилась в списке?

2024-09-23 09:22 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +                    1000, q, [this] { QApplication::postEvent(q, new DesignSystemChangeEvent); });
да, без этого инфа обновится только при наведении курсора

2024-09-23 09:26 UTC, dimkanovikov commented
Слушай, а может нам тут пойти другим путём - не обновлять инфу о проекте на стартовой странице до тех пор, пока он не был сохранён с изменениями?

2024-09-23 09:31 UTC, iljukhaput commented
хмм... принял, переделаю)

2024-09-23 09:36 UTC, dimkanovikov commented
я скорее хотел спросить - что если такой подход рассмотреть? будет нам от этого лучше вообще? не смутит ли пользователей, что у них тексты/картинка не сразу обновляется, а только после сохранения?

2024-09-23 09:41 UTC, iljukhaput commented
ну кстати да, немного неожиданное поведение получится, как мне кажется.
А что если нам спрашивать пользователей о сохранении при выходе из проекта на главный экран?

2024-09-23 15:31 UTC, iljukhaput commented
переделал, перезалил

2024-09-23 18:17 UTC, dimkanovikov commented
Как по ощущениям, стало лучше?)

2024-09-24 02:43 UTC, iljukhaput commented
сложно сказать какой из вариантов лучше с точки зрения пользователей)
но вроде вполне логичный вариант, если рассматривать список проектов, как список именно сохраненных
а в плане кода стало однозначно поаккуратнее

2024-09-24 02:50 UTC, iljukhaput commented
кстати, тут понял, что осталась проблема с обложкой:
- уже есть обложка
- установил новую
- не сохранил
- в итоге обложки нет вообще

сейчас это поправлю, перезалью

2024-09-24 07:42 UTC, iljukhaput commented
перезалил

плюс добавил обработку такого случая:
- устанавливаем новую обложку
- не сохраняя, снова устанавливаем новую обложку
- сохраняем

в итоге в БД записывается только последняя обложка, а не обе

2024-09-30 10:01 UTC, dimkanovikov requested changes

2024-09-30 14:25 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +    QTimer::singleShot(_timeout, q,
в таком случае обновляется только при наведении курсора на карточку проекта

2024-09-30 14:38 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +    QTimer::singleShot(_timeout, q,
https://github.com/user-attachments/assets/d4c8c825-f2b4-49a9-87b9-454a0745c81c

вот так)

2024-09-30 16:03 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    QTimer::singleShot(_timeout, q,
Я это понимаю, что оно не работает. И предлагаю разобраться в том, почему оно не работает, ведь вроде есть сигнал об обновлении, значит вьюха должна соответствующий этому проекту элемент перерисовать. Кидая событие обновления дизайн системы мы стреляем из ракетницы по воробьям, грубо говоря.

2024-10-01 15:23 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +    QTimer::singleShot(_timeout, q,
разобрался, исправил

2024-10-01 15:23 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +    } projectsListChanges;
переделал

2024-10-01 15:28 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +    QTimer::singleShot(_timeout, q,
до отправки сигнал дело не доходило из-за того, что итем в модели не был помечен, как измененный

2024-10-07 16:03 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    projectManager->clearCoverBuffer();
почему мы делаем это тут, а не внутри метода сохранения измененеий менеджера проекта?

2024-10-07 16:08 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> -    connect(d->projectManager.data(), &ProjectManager::projectNameChanged, this,
вот тут мы убираем обновление инфы о проекте - как она теперь обновляется при открытии проекта?

2024-10-07 16:24 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +    } coverBuffer;
так, а зачем нам тут буфер нужен? почему не получается использовать просто одно изображение?

2024-10-07 16:27 UTC, dimkanovikov commented
Смотрю я короче на него и он мне не нравится) как будто должно быть всё как-то проще, типа если изменения ввели и пользователь сохраняет проект - они обновились на странице проектов, если не сохранил, то список проектов остался в том виде, в котором был...

сейчас получается как-то наворочено, буфер, методы очистки буфера торчат во все стороны))) хочется максимально тупого решения что ли

2024-10-08 04:22 UTC, iljukhaput commented
так, вернусь тогда к этой задаче после ремарок, ок?
а то чувствую это не будет быстро)

2024-10-08 04:24 UTC, dimkanovikov commented
Да, конечно.

2024-10-15 04:48 UTC, closed without merging