Fix an updating of the start page
story-apps/starc pull request #281
Opened 2024-10-28 17:06 UTC by iljukhaput

2024-10-29 07:59 UTC, iljukhaput commented
Кстати, небольшая ремарка:
сделать установку обложки аналогично текстовым данным не получилось, обложка при установке все же сохраняется в бд сразу. 
Оставил так, потому что после установки новой обложки формируется патч, для которого нужен uid, а его мы получаем при сохранении обложки

2024-11-07 06:44 UTC, dimkanovikov reviewed
Так, получилось отлично. Но всё равно не нравится необходимость удалять вручную обложки. А если нам докрутить так, чтобы юид обложки формировался, но картинка в базу не сохранялась при этом?

2024-11-07 06:44 UTC, dimkanovikov commented on src/core/management_layer/content/projects/projects_model_project_item.cpp
> +    setChanged(true);
(тут и ниже) помечаем изменённым по идее после того, как изменение попало в модель

2024-11-07 14:26 UTC, iljukhaput commented on src/core/management_layer/content/projects/projects_model_project_item.cpp
> +    setChanged(true);
исправил

2024-11-07 14:27 UTC, iljukhaput commented
> А если нам докрутить так, чтобы юид обложки формировался, но картинка в базу не сохранялась при этом?

докрутил)

2024-11-08 02:35 UTC, iljukhaput commented
так, я тут заметил, что удаление старой обложки было неправильно - это поправил, перезалил уже;
и ещё один баг нашел - если загрузить новую обложку и, не сохраняя, попытаться удалить её, она не удалится - это сейчас поправлю и снова перезалью

2024-11-08 03:26 UTC, iljukhaput commented
поправил, перезалил

2024-11-12 08:03 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +            &ProjectsManager::updateCurrentProject);
а зачем нам тут делать это? ведь мы можем сразу в менеджере приложения в момент сохранения изменений, после того, как сохранили изменения проекта, сохранить и его параметры? выглядит, как будто можно сделать проще, без этой перелинковки сигналов/слотов

2024-11-12 08:12 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +            &ProjectsManager::updateCurrentProject);
плюс немного логика сбивается, имхо, мы там сохраняем изменения вообще из всех документов проекта, а уведомление кидаем чисто из модели информации о проекте)

2024-11-12 08:14 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
а зачем нам это тут делать? почему нельзя оставить как было раньше и дальше полагаться на методы сохранения/очистки хранилища в менеджере проекта?

имею в виду `DataStorageLayer::StorageFacade::documentChangeStorage()->store();` и т.д.

2024-11-20 10:33 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +            &ProjectsManager::updateCurrentProject);
переделал

2024-11-20 10:36 UTC, iljukhaput commented on src/core/management_layer/application_manager.cpp
> +    void updateWindowTitle(const QString& _projectName = QString{});
исправил

2024-11-21 10:49 UTC, dimkanovikov commented on src/core/management_layer/content/projects/projects_manager.cpp
> +    setCurrentProjectCover(_cover);
а все методы, которые тут внутри используются они откуда-то извне ещё используются теперь? или может их уже можно удалить?

2024-11-21 10:52 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
а зачем нам их вообще хранить? это же задача враппера изображений, он должен этим заниматься, а мы его просто используем через интерфейс, а потом в момент сохранения, пусть он что нужно пишет в базу (добавляя, удаляя изображения)

мне кажется нужно там докручивать, а тут упростить по максимуму

2024-11-25 08:49 UTC, iljukhaput commented on src/core/management_layer/content/projects/projects_manager.cpp
> +    setCurrentProjectCover(_cover);
они все используются ещё в менеджере приложения

2024-11-25 15:53 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
Супер! Следущий вопрос) а нам реально нужно два метода удаления? можем оставить один?) ведь нам как клиенту неважно что там делается внутри - удаляются ли они физически, или помечаются для удаления...

2024-11-25 16:40 UTC, iljukhaput commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
да, действительно, прямое удаление больше не нужно, кажется
но лучше отдельным коммитом это сделать - там нужно будет внести изменения в модели данных мира, локации, персонажа и галереи изображений

2024-11-25 16:55 UTC, iljukhaput commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
да, действительно)
исправил

2024-11-25 18:10 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
Топчик! Последний (кажется) момент - я бы сигнал всё таки о том, что изображение удалено выдавал именно в момент вызова метода `remove`, чтобы клиенты класса могли корректно обновлять интерфейс и т.п. вещи делать, связанные с реакцией на данный сигнал

2024-11-26 02:16 UTC, iljukhaput commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
перенес
а этот сигнал где-то в приватных модулях подключен? 
а то не нашел ни одного упоминания кроме отправки

2024-11-26 04:50 UTC, dimkanovikov commented on src/corelib/data_layer/storage/document_image_storage.cpp
> +        if (!d->imagesToRemove.removeOne(imageIter.key())) {
может быть при удалении сразу и проверять, есть ли он в списке новых и если есть, то убирать из списка?

2024-11-26 04:51 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +}
посмотрел - он нигде пока не используется) но хорошо, что перенесли, с точки зрения логики он теперь по месту расположен

2024-11-26 05:26 UTC, iljukhaput commented on src/corelib/data_layer/storage/document_image_storage.cpp
> +        if (!d->imagesToRemove.removeOne(imageIter.key())) {
сделал

2024-11-26 06:03 UTC, dimkanovikov requested changes

2024-11-26 06:03 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +    ProjectInformationModel* q = nullptr;
это можно убрать теперь

2024-11-26 06:03 UTC, dimkanovikov commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +    // Если ранее обложка была задана, то добавим её в список на удаление
старый коммент в целом тоже можно оставить, т.к. мы не делаем предположений о том, как внутри устроен класс, а работаем с интерфейсом

2024-11-26 06:03 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    auto projectInformationModel = qobject_cast<BusinessLayer::ProjectInformationModel*>(
тут и ниже предлагаю добавить константы

2024-11-26 06:19 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    auto projectInformationModel = qobject_cast<BusinessLayer::ProjectInformationModel*>(
добавил

2024-11-26 06:19 UTC, iljukhaput commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +    // Если ранее обложка была задана, то добавим её в список на удаление
вернул

2024-11-26 06:20 UTC, iljukhaput commented on src/corelib/business_layer/model/project/project_information_model.cpp
> +    ProjectInformationModel* q = nullptr;
убрал

2024-11-26 07:26 UTC, merged