Prohibit editing documents in the trash
story-apps/starc pull request #282
Opened 2024-10-30 14:37 UTC by iljukhaput

2024-11-01 08:12 UTC, dimkanovikov requested changes

2024-11-01 08:12 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            inactiveView->setEditingMode(DocumentEditingMode::Read);
не понял зачем тут нужно это делать, в каком кейсе это может понадобиться?

2024-11-01 08:12 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (auto view = d->activeDocumentView(); view != nullptr) {
тут как я понял кейс, когда кладут элемент в корзину, или вытаскивают из неё?

2024-11-01 08:12 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            inactiveView->setEditingMode(DocumentEditingMode::Read);
вот это не понял тоже зачем нужно делать, другая вьюха разве не была настроена уже?

2024-11-01 08:12 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +                             : d->documentEditingMode(_item));
может быть нам это всё завернуть внутрь `documentEditingMode`?

2024-11-01 08:12 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    }
и тут зачем-то опять мы настраиваем режим редактирования?

2024-11-01 12:12 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            inactiveView->setEditingMode(DocumentEditingMode::Read);
да, действительно, здесь не нужно
убрал

2024-11-01 12:13 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (auto view = d->activeDocumentView(); view != nullptr) {
да
сейчас немного переоформил и подключил к другому сигналу, чтобы можно было положить метод `isInRecycleBin` внутрь `documentEditingMode`

2024-11-01 12:13 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            inactiveView->setEditingMode(DocumentEditingMode::Read);
была настроена, да
но режим редактирования сбрасывается у неё при переключении

2024-11-01 12:13 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +                             : d->documentEditingMode(_item));
сделал

2024-11-01 12:13 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    }
в `switchViews` убрал, тут оставил

2024-11-01 12:20 UTC, iljukhaput commented
вообще, тут основная проблема в том, что при разделении на два экрана режим редактирования у неактивной вьюхи сбивается
сейчас понял, что это решение больше похоже на устранение симптомов (как с обновление обложек было)
давай я лучше ещё в этом покопаюсь, потом перезалью

2024-11-01 12:57 UTC, dimkanovikov commented
да, хорошо

2024-11-06 09:31 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +                                                    d->isInRecycleBin(itemForShow));
смотри, там ниже для вьюхи уже настраивается режим редактирования и с новыми правками, как я понимаю проверка того, что элемент в корзине будет выполнена внутри `d->documentEditingMode`

2024-11-06 09:32 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        view = d->pluginsBuilder.activateView(viewMimeType, d->view.activeModel,
тут тоже самое, плюс я бы ещё вот эту проверку `_item->isReadOnly()` тоже перекинул в `d->documentEditingMode`, что думаешь?

2024-11-06 09:35 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +                                              d->isInRecycleBin(item));
в этом кейсе и ниже, тогда уже давай сделаем, чтобы было консистентно с предыдущими двумя и добавим вниз явную настройку режима редактирования с полной проверкой, а не только корзины

2024-11-06 09:49 UTC, dimkanovikov commented on src/core/management_layer/plugins_builder.cpp
> -    plugin->setEditingMode(editingMode);
смотри тут ещё какая проблема, когда мы откроем другой проект, из облака, который нам доступен только для просмотра, нужно будет перенастроить доступность тех вьюх, которые уже были открыты, поэтому тут был этот метод

2024-11-06 09:51 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +                                                    d->isInRecycleBin(itemForShow));
да, тут получается дублирование этой проверки, т.к. сама установка режима редактирования тоже дублируется: в `d->pluginsBuilder.activateView`/`activateSecondView` и ниже непосредственно `view->setEditingMode`

2024-11-06 11:17 UTC, iljukhaput commented on src/core/management_layer/plugins_builder.cpp
> -    plugin->setEditingMode(editingMode);
Если я правильно понимаю, новый проект открывается всегда изначально в режиме одного окна.
Не достаточно ли в этом случае того, что ниже мы устанавливаем режим редактирования для активной вьюхи?

Проблема с тем, что сбрасывается запрет редактирования в корзине для неактивной вьюхи, как раз в этом и заключается, что при вызове `PluginsBuilder::Implementation::activatePlugin` режим редактирования переустанавливается для всех вьюх плагина внутри `plugin->setEditingMode(editingMode);`

2024-11-06 11:28 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        view = d->pluginsBuilder.activateView(viewMimeType, d->view.activeModel,
кстати да, проверку `_item->isReadOnly()`  думаю логично будет перекинуть.
а вот с дублированием `d->isInRecycleBin(_item)` немного не понимаю: внутри `PluginsBuilder` мы же не можем узнать в корзине итем или нет, но эдит мод мы там устанавливаем, поэтому я решил передать в виде параметра результат этой проверки

2024-11-07 06:14 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +                                                    d->isInRecycleBin(itemForShow));
переделал: убрал передачу третьего параметра в эти методы

2024-11-07 06:14 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        view = d->pluginsBuilder.activateView(viewMimeType, d->view.activeModel,
да, действительно, `_item->isReadOnly()` перекинул

2024-11-07 06:15 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +                                              d->isInRecycleBin(item));
сделал
только настройку режима редактирования сделал для обеих вьюх (по сути, практически вернулся к предыдущему варианту)

2024-11-07 06:15 UTC, iljukhaput commented on src/core/management_layer/plugins_builder.cpp
> +            // #ifndef QT_NO_DEBUG
клэнг формат автоматом сделал
убрал

2024-11-07 06:17 UTC, iljukhaput commented on src/core/management_layer/plugins_builder.cpp
> -    plugin->setEditingMode(editingMode);
этот вызов вернул в итоге

2024-11-07 06:37 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        addFolder->setEnabled(enabled && !isInRecycleBin(currentItem));
хорошая попытка, но давай это сделаем в отдельном реквесте) заведи плиз отдельную задачку на доработку контекстного меню документов, которые в корзине лежат. Я бы предложил для них оставить там только возможности удалить навсегда и свернуть/развернуть дерево.

2024-11-07 06:37 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    }
давай сюда добавим тудушку, или докрутим, что мол ещё нужно обновить режим редактирования для вьюх, которые открыты в отдельном окне

2024-11-07 06:37 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
а зачем нам тут для обеих вьюх обновлять состояние? нельзя для текущей настраиваемой это сделать только?

2024-11-07 06:37 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
тут и ниже соответственно ткой же вопрос)

2024-11-07 06:37 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
а вот тут у нас вообще навигатор настраивается, а вьюхи не трогаются, тут точно нужно это делать?

2024-11-07 08:03 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
косяк, да...
убрал

2024-11-07 08:04 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
если мы разделим экран и переключим одну вьюху на другой итем, то у второй вьюхи тоже обновится состояние. 
Так происходит, потому что методы плагинов устанавливают режим для всех вьюх, например:

```
void ScreenplayInformationManager::setEditingMode(DocumentEditingMode _mode)
{
    for (auto& viewAndModel : d->allViews) {
        if (viewAndModel.view.isNull()) {
            continue;
        }

        viewAndModel.view->setEditingMode(_mode);
    }
}
```

2024-11-07 08:04 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
здесь по той же причине, соответственно)

2024-11-07 08:04 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    }
докрутил)

2024-11-07 08:14 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        addFolder->setEnabled(enabled && !isInRecycleBin(currentItem));
изменения убрал, задачку завел

2024-11-08 08:38 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
Может быть тогда их разведём? ну или как-то докрутим так, чтобы типа режим редактирования вьюхи настраивался внутри только в кейсе её создания, или вообще уберём его оттуда. При этом добавим настройку режима редактирования для всех вьюх, при смене проекта. Что думаешь?

2024-11-08 08:51 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
да, кстати, я думал о том, чтобы вообще убрать установку эдит мода внутри вьюх, но мне показалось это слишком кардинальные изменения))
но раз ты тоже говоришь, то переделаю так
думаю лучше именно вообще убрать, т.к. вьюха может же создаваться и для итема, который уже в корзине

2024-11-08 08:55 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
да, согласен, давай в это направление попробуем пойти

2024-11-12 06:27 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    d->updateViewsEditingMode();
сделал

2024-11-12 08:53 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            QWidget* asQWidget = nullptr;
может быть это в метод переделать, чтобы лишних указателей не хранить?

2024-11-12 08:53 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            Ui::IDocumentView* asView = nullptr;
а тут предлагаю просто `view` назвать, а то выглядит больше как имя метода, чем имя члена структуры

2024-11-12 08:53 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            QCoreApplication::sendEvent(window.asQWidget, _event);
выше в цикле тогда видимо лучше использовать константные указатели на окна

2024-11-12 08:53 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    view->setEditingMode(d->documentEditingMode(item));
тут точно нужно настроить режим редактирования? мы же убрали его перенастройку из метода активации, зачем он тут?

2024-11-12 09:37 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    view->setEditingMode(d->documentEditingMode(item));
да, действительно, не нужно
убрал

2024-11-12 09:38 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            QCoreApplication::sendEvent(window.asQWidget, _event);
сделал

2024-11-12 09:38 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            Ui::IDocumentView* asView = nullptr;
переименовал

2024-11-12 09:42 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            QCoreApplication::sendEvent(window.asQWidget, _event);
сорян, имел в виду константные ссылки конечно)

2024-11-12 09:53 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            QCoreApplication::sendEvent(window.asQWidget, _event);
сделал)
я сам не сразу обратил внимание, что там по значению бралось

2024-11-12 09:58 UTC, merged