Clarify the context menu of documents in the recycle bin
story-apps/starc pull request #285
Opened 2024-12-10 15:35 UTC by iljukhaput

2024-12-10 15:37 UTC, iljukhaput commented
Если то, про что в тг спрашивал, не нужно, то готово)

2025-01-30 08:50 UTC, dimkanovikov commented
> Если то, про что в тг спрашивал, не нужно, то готово)

Напомни, плиз, я тебе отвечал на тот вопрос?)

2025-01-30 08:59 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (currentItem->type() == Domain::DocumentObjectType::Characters) {
Знаешь, что подумал - сейчас, если у нас выделено несколько элементов не в корзине и мы вызовем контекстное меню, то оно будет показано для последнего выделенного, что кажется не совсем корректным с точки зрения логики пользователя. Давай ещё добавим кейс, что если выделено несколько элементов за пределами корзины, то доступны действия добавления новых, удаления выделенных и сворачивания/разворачивания. И получается, у нас останется кейс, когда выделен один элемент и он не в корзине и тогда ему показываем список его уникальных действий.

2025-01-31 07:47 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (currentItem->type() == Domain::DocumentObjectType::Characters) {
сделал
Плюс сделал, чтобы при удалении из корзины в диалоге с вопросом "точно ли удалить?" показывалось имя файла. Потому что при удалении из корзины этот диалог для каждого файла появляется. 
Вообще, может тут подправить, чтобы он только один раз появлялся?

Ещё для случая, когда выделенные элементы и в корзине, и вне её, сделал чтобы можно было только свернуть/развернуть. А то было так, что элементы вне корзины перемещались в корзину, а в корзине удалялись навсегда. В общем, мне показалось как-то не хорошо, что разная логика для одного действия.

2025-01-31 07:49 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (currentItem->type() == Domain::DocumentObjectType::Characters) {
и коммит переименовал)

2025-02-04 07:38 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (currentItem->type() == Domain::DocumentObjectType::Characters) {
> Вообще, может тут подправить, чтобы он только один раз появлялся?

Это отличная идея!

2025-02-04 07:49 UTC, dimkanovikov requested changes

2025-02-04 07:49 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +    bool noOneInRecycleBin = true;
Вот тут предлагаю чуть переименовать `allInsideRecycleBin` + `allOutsideRecycleBin`, или что-то в этом стиле. Когда в имени присутствует отрицание - это, как правило, сложно читать/понимать.

2025-02-04 07:49 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (_index.isValid() && selectedIndexes.size() == 1 && isTextItem(currentItem)) {
тут и ниже условие `selectedIndexes.size() == 1` можно убрать, т.к. оно у нас уже выше проверяется

2025-02-04 07:49 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (_index.isValid() && selectedIndexes.size() == 1 && isTextItem(currentItem)) {
`_index.isValid()` тоже можно вынести выше сразу

2025-02-06 09:30 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +        if (currentItem->type() == Domain::DocumentObjectType::Characters) {
> подправить, чтобы он только один раз появлялся?

сделал

2025-02-06 09:30 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +    bool noOneInRecycleBin = true;
переименовал

2025-02-06 09:30 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (_index.isValid() && selectedIndexes.size() == 1 && isTextItem(currentItem)) {
сделал

2025-02-06 13:30 UTC, dimkanovikov commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (_index.isValid() && selectedIndexes.size() == 1 && isTextItem(currentItem)) {
`_index.isValid()` имел в виду перенести туда, где проверяем условие `selectedIndexes.size() == 1` и дальше идёт обработка одного элемента, в других кейсах оно вроде не актуально

2025-02-06 14:20 UTC, iljukhaput commented on src/core/management_layer/content/project/project_manager.cpp
> +            if (_index.isValid() && selectedIndexes.size() == 1 && isTextItem(currentItem)) {
исправил
и добавил проверку в начало, а то при невалидном индексе было 
`allInsideRecycleBin = true; allOutsideRecycleBin = true;`

2025-02-06 17:52 UTC, merged